### ISSUE TITLE
RAW Capability

### ISSUE THREAD

**Issue by davidangel** [electerious/Lychee#110]
I'm not too sure what all would be involved with allowing for various RAW formats, but that would be totally sick.

Looks like the ImageMagick library (#107) supports Nikon and Canon RAW formats out of the box...

**Comment by ipleten** [comment]
Any updates/plans?

**Comment by mickael-kerjean** [comment]
I've released a new version of [nuage](https://github.com/mickael-kerjean/nuage/wiki/Release-0.2:-Photo-Management) that provide support for those: CR2, CRW, DNG, NEF, NRW, TIFF, TIF, RAW, RW2, ARW, SR2, MDC, MRW, ORF, PES, X3F, ERF, RAF, 3FR, MEF, MOS, SRW, DCR, KDC

**Comment by cowai** [comment]
@electerious I would recommend using exiftool. It depends on perl but almost every server has that.
Exiftool also is available with composer.
Here is some inpiration for super simple code: https://github.com/cowai/camerarawpreviews/blob/master/lib/RawPreview.php

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
