### ISSUE TITLE
Ability to rotate photographs

### ISSUE THREAD

**Issue by djdallmann** [electerious/Lychee#131]
A nice feature addition would be to be able to rotate photographs 90,180 clockwise and counter-clockwise. This could be implemented as a right click option for the thumbnail view or while viewing an individual picture.

**Comment by etano** [comment]
Any work on this front? +1

**Comment by d6e** [comment]
+1

**Comment by vjrj** [comment]
+1

**Comment by jswetzen** [comment]
I'm looking into implementing this, but after scratching the surface it seems trickier than I thought. I thought of two ways of rotating: the actual image or the EXIF Orientation tag. EXIF is the way to go for lossless rotation and I verified that this  method has an effect in Lychee (using Chrome on Mac with the server running on Apache on Mac).

Apparently, [EXIF Orientation Handling Is a Ghetto](http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/); most websites and even some browsers get it wrong. So I can try to do a correct implementation but there are no guarantees that every system displays it properly.

Another issue is that EXIF is only for JPG and TIF, so PNG for example would have to be rotated normally. For PNG there's no data loss but I don't know what other formats are supported and how they would work.

My idea now, to get going, is to use EXIF but only enable rotation for JPG, which is the most common format anyway.

**Comment by jswetzen** [comment]
This is my first venture into the Lychee codebase, so I didn't know that EXIF data is stripped if an image has an EXIF orientation set and has to be rotated. That's a bit of a showstopper for me as I was hoping for lossless photo organization on ownCloud using lycheesync.

If the orientation was saved in the db instead and rotated when shown (except for thumbnails which would be rotated on creation), this could be avoided. Is this the only case where the original image is modified?

**Comment by electerious** [comment]
I don't remove the EXIF data actively, but it looks like `imagecreatefromjpeg` does. That should only happen when a EXIF orientation is set. Lychee must rotate the full-photos so all browsers and operating systems show them in the same way. Yes, EXIF orientation handling is a ghetto :-/

Lychee uses Imagick when installed on the server. Maybe Imagick keeps the EXIF data. Could be worth a look.

**Comment by jgreth** [comment]
+1

**Comment by n1md4** [comment]
+1

**Comment by mhellwig** [comment]
so, for clarification, since rotation within Lychee is not (yet) supported, what would be the workflow in my case?
I have created an album with ~800 pictures in it. A lot of them are already tagged and all of them are titled. So I'm not going to start over again .. Some of them are not rotated correctly. What would be the ideal way to correct them? Take the source pictures, rotate them, upload them and add to the album, deleting the incorrect ones? Or what would Lychee do if I rotate its jpegs on the server with some console tool (jpegtran or whatever)? I presume that would lead to a disconnect between the data in the file and the metadata in the database, right?

Please enlighten.

**Comment by electerious** [comment]
>  Or what would Lychee do if I rotate its jpegs on the server with some console tool (jpegtran or whatever)? I presume that would lead to a disconnect between the data in the file and the metadata in the database, right?

That's correct. You need to rotate them on the server (`uploads/thumb`, uploads/medium`, uploads/big`) and fix the width and height in the database.

**Comment by mostlyjason** [comment]
+1

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
