### ISSUE TITLE
Ability to have longer titles in photos and albums

### ISSUE THREAD

**Issue by grantlucas** [electerious/Lychee#144]
I've just started checking out Lychee and have already run into some of the limits that are set in place. For example, a character limit of 30 for titles on albums is very small.

Are you open to increasing the max length of titles? Was there an initial reasoning behind the 30 character limit?

On a side note, thanks for creating a really nice self hosted photo tool. I'll be making contributions in the future to help out with development!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
