### ISSUE TITLE
[Feature] upload a full directory

### ISSUE THREAD

**Issue by seboudry** [electerious/Lychee#162]
Hi !
Is there a way to implement the directory html5 attribute :
http://www.w3bees.com/2013/03/directory-upload-using-html-5-and-php.html

The idea is to select a client-side directory, this will create a new album with the same name and upload all pictures in it.

Thanks for the job :)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
