### ISSUE TITLE
Album view crashes Safari on iOS

### ISSUE THREAD

**Issue by krejac** [electerious/Lychee#167]
I have an album with ~800 photos in it. It works great in desktop browsers but crashes consistently on iOS (iPhone 5 and iPad mini retina). 

Any ideas why?

**Comment by Unresponsive** [comment]
Paginating albums and images in albums (with admin selectable per-page limit) would really help!

Mobile Safari keeps crashing on me with a 500 image album. It also takes forever to load.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
