### ISSUE TITLE
[Suggestion] GPS tag in photo info

### ISSUE THREAD

**Issue by phunatix** [electerious/Lychee#180]
Are there plans to display a small map beneath the EXIF information where that photo was taken? 

Based on the tags I am writing into the files it should be possible to extract the altitutde/longitutde coordinates and to display this via iframe/script into e.g GMaps.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
