### ISSUE TITLE
[Suggestion] Preload the next picture to watch

### ISSUE THREAD

**Issue by RSaultier** [electerious/Lychee#185]
When we're watching a picture, it could be interesting to load in memory/cache, the next picture, or even the 2 next pictures, in order to have a more comfortable watching. (if it is technically possible).

**Comment by 1337sup3rh4x0r** [comment]
I would love to see this return to Lychee's feature list! When showing pictures outside my home, it can be kind of tiring. Are you planning to find a solution for this?

**Comment by chrismarquardt** [comment]
+1

The image loading behavior really is the biggest sore point for me, it
takes away so much from the otherwise stellar user experience. I really
love the bounce when images are in cache, it makes a positive feeling.

**Comment by 1337sup3rh4x0r** [comment]
Well the bounce might be nice, but more importantly I would like to be able to minimize blank screen times when showing pictures to others. 

The audience's attention is lost too easily ;)

**Comment by electerious** [comment]
Here's more about the technical problem: https://github.com/electerious/Lychee/issues/361#issuecomment-111722979

**Comment by LudovicRousseau** [comment]
I just discovered that the "next" and "previous" buttons contains a preview (thumb) of the corresponding next and previous image.
If, instead of a preview (thumb), Lychee displays the *full* images then the image will be fetched by the browser and will be cached by the browser for the full display.

Side effects:
* The next and previous buttons background images will be slower to load but that should be transparent for most users.
* Also the display of the first image would load 3 full size images (main image + background for next and previous buttons) but that is the price to pay to have images preload.

**Comment by kgraefe** [comment]
You still have to make sure that the current image will be loaded first.

**Comment by LudovicRousseau** [comment]
@kgraefe That is not possible.
The price for preload is that (at most) 3 images are loaded at the same time. This should happen *only* for the first image of the album. After that, the next (or previous) image is already available in the browser cache so will be displayed immediately.

**Comment by kgraefe** [comment]
It still doesn't sound like a clean solution to me and it will make things worse for people that don't care about this issue but loading time (and that nobody figured out how to do it properly yet does not mean that it is not possible. ;-)).

However it's not me to define the priorities of Lychee here.

**Comment by 1337sup3rh4x0r** [comment]
I think this sounds like the ideal solution! I encourage to take this path :)

**Comment by LudovicRousseau** [comment]
I finally found some time to implement my idea. See patch at https://github.com/LudovicRousseau/Lychee/commit/49137c7a415018f5aef74be14e1c8237ec5d3e62

The idea is to use the next image as the background image of the "next image" button. You can see that the background image is not displayed immediately. But if you go to the next image you immediately get the animation and the next image instead of a back screen.

I have not changed the "previous image" button. The previous image should already be in the browser cache.

You can try by yourself by cloning my prefetch branch https://github.com/LudovicRousseau/Lychee/tree/prefetch. The files have been regenerated. @kgraefe and all, please test it and comment.

**Comment by LudovicRousseau** [comment]
A new updated version of my patch (to match current master) is at https://github.com/LudovicRousseau/Lychee/commit/bdebfb0afad05a8511d3b0f6ab1bbfde98c1c154

**Comment by electerious** [comment]
`prefetching` cloud be the perfect solution for this issue.

> If we're certain that a specific resource will be required in the future, then we can ask the browser to request that item and store it in the cache for reference later. For example an image or a script, or really anything that's cacheable by the browser […] prefetching can be ignored by the browser. For example, a client might abandon the request of a large font file on a slow network. Firefox will only prefetch resources when "the browser is idle".

Just tested it with Chrome and it also works when adding the prefetch-link via JS.

```js
$('head').append('<link rel="prefetch" href="test.jpg">')
```

Source: https://css-tricks.com/prefetching-preloading-prebrowsing/

**Comment by LudovicRousseau** [comment]
@electerious ``prefetching`` looks like the perfect solution. Please implement it.

For users that do not want to prefetch the next image they can disable it, at least in Firefox https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ#Is_there_a_preference_to_disable_link_prefetching.3F

**Comment by electerious** [comment]
It's also possible to disable it in Chrome, but I think the browser knows best when to prefetch. Will implement it!

**Comment by chrismarquardt** [comment]
\o/

**Comment by electerious** [comment]
Prefetch works fine in my tests, but the bounce animation is still missing when opening big photos. It takes a while for the browser to render/scale the cached image.

Another problem:
The size of the next image is unknown and Lychee always preloads the big photo, but sometimes only displays the medium/down-scaled version.

Possible solutions:
a) Load both versions of the next photo
b) Use the size of the current photo to hope that the next one will have the same size

**Comment by chrismarquardt** [comment]
Option b) would work just fine for me. My Lychee albums typically have
pictures all of the same size.

**Comment by electerious** [comment]
Will go with b) but need to implement additional checks to ensure that a medium-version is available for the next photo.

**Comment by electerious** [comment]
I also realized that—even when preloading the images—the bounce animation isn't visible for big photos. It simply takes time for the browser to load, scale and render it.

**Comment by LudovicRousseau** [comment]
The patch in https://github.com/electerious/Lychee/commit/6464d6bcc639c39d968f0c31b96fa5559164a648 does not work for me.
I use Firefox 42.0. Using the Development tools I see that the next image is loaded only when I click on the "next image" button or use the keyboard right arrow.

I also do not see the "data-prefetch" in the request header. Something is broken.

Maybe that explains why you do not see the bounce animation.

**Comment by palitu** [comment]
Thanks Electerious - I don't know if you have implemented the 'b' option yet, but it would definitely be the best solution.  I would have thought that the majority of people would want to share the medium sized photo, so that they load quicker, without the slow network speeds.

**Comment by electerious** [comment]
@LudovicRousseau Just tested it, again. Works fine for me. Here's how Chrome shows a prefetch.
![developer tools - https l electerious com](https://cloud.githubusercontent.com/assets/499088/12198837/aef736ea-b613-11e5-9348-5043a7407e22.png)

**Comment by electerious** [comment]
@palitu 'b' hasn't been implemented, yet. Here's why: 

The next version of Lychee uses `<img>`, instead of `background-image`. I found a way to center an `<img>` vertical and horizontal, while maintaining the aspect ratio and ensuring that the image stays within the surrounding box. This allows me to use `srcset`, so the browser can decide if it should display the medium or big version. They can use different parameters to make a smarter decision.

One downside: Lychee isn't aware of what the browser displays. This means we need to prefetch both versions.

**Comment by palitu** [comment]
right, i would go for the assumption that if medium is enabled, then
pre-fetch the medium.

just so i get it straight in my head, if medium is enabled, then all
galleries will show the medium picture?  is the edge case where the
original is smaller than the medium size?

either way, keep up the great work!  I love it!

**Comment by electerious** [comment]
@palitu Lychee will generate a medium version when the photo is bigger than 1920x1080. It will only show the medium version when the screen is smaller than 1920x1080 or when the browser decides to do so. The pixel density of your screen will also affect those decision.

**Comment by LudovicRousseau** [comment]
@electerious that is quiet strange. For my new test I used Chrome 47.0.2526.106 (64-bit) and the website https://l.electerious.com/ to be sure to run the same code.
I still do not have the prefetch in the headers.
And it is clear the next image is NOT prefetched. it is slow to download and display.
![capture d ecran 2016-01-08 a 20 46 21](https://cloud.githubusercontent.com/assets/398496/12207812/1e5db722-b649-11e5-948e-ade62462851b.png)

Do you have enabled an option in Chrome to support prefetch?

I also checked with Firefox 43.0.4 and Safari 9.0.2 and no prefetch as well.

**Comment by electerious** [comment]
Looks like there's a setting for it: https://support.google.com/chrome/answer/1385029?hl=en

**Comment by LudovicRousseau** [comment]
I just discovered that the Firefox module uBlock Origin https://addons.mozilla.org/fr/firefox/addon/ublock-origin/ disables the Firefox ``network.prefetch-next`` option https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

But that does not explain why if does not work either on Chrome and Safari.

**Comment by LudovicRousseau** [comment]
An even with Firefox option ``network.prefetch-next`` set to ``true`` I still do not have prefetch on Firefox :-(

**Comment by electerious** [comment]
Not sure why. Maybe your browser decides not to prefetch due to your connection/device/environment. [Safari does not support prefetching](http://caniuse.com/#feat=link-rel-prefetch).

**Comment by palitu** [comment]
is there a cheeky way of getting the photo into cache?  actually include it
in the page, but ensure that it is invisible?

i think you had the thumbnails for prev and next as full size images, just
shrunk to fit.

we would just need to ensure that the load order is enforced if possible.

**Comment by electerious** [comment]
Yes, there're several ways to get a photo into cache, but prefetch looked like the best solution. Browser know when it's ok to preload images. They know when you're on a mobile device/network and when other resources finished loading. Lets use it for a while and see if we need to try a different approach.

**Comment by Bramas** [comment]
@LudovicRousseau Do you have medium size photo enabled? Because if I understand well, prefetch is enabled only for medium size photo and it seems the example website https://l.electerious.com/ does not have medium size so it cannot be used to test the feature.
tell me if I'm wrong.

**Comment by LudovicRousseau** [comment]
@Bramas I wanted to reuse the same site as @electerious used in https://github.com/electerious/Lychee/issues/185#issuecomment-170003380.
It worked for @electerious but not for me. That is strange. The problem may not be on the server side but on the client side with the prefect feature.

I think I will continue maintaining my patch that loads the next image in the "next" button icon. At least that works for me :-)

**Comment by Bramas** [comment]
Ok I did not see that it works for @electerious with the same example.
I understand your problem, however I don't understand how this feature is supposed to work **without** medium size photo enabled. I thought this had to be enabled.

**Comment by Bramas** [comment]
OK I found something.
First of all, when you said it didn't work for you @LudovicRousseau, you actually didn't selected the right file in the your screenshot of the developper panel:
![sreenshot](https://cloud.githubusercontent.com/assets/398496/12207812/1e5db722-b649-11e5-948e-ade62462851b.png)
You selected the current photo and you can see that there is another photo juste after (name start with b1e...) and this one is actually prefetched as @electerious pointed out in its own sreenshot.
This is the how it is supposed to work: the **next** photo is prefetched.

But there is a bug (but somewhere else):
If you look at the url of the prefetch photo (in the screen shot of @electerious at least, and with my in my own lychee website), **the next BIG photo is prefetch instead of the medium one**
That's something we have to fix!!

**Comment by prat0088** [comment]
If the next picture is preloaded I assume that will make swiping through pictures smoother on iPhone. The lack of smooth swipe on iPhone is the biggest pain point for me because all of the people who I will be sharing Lychee galleries with use smart phones to view.   Without prefetching Lychee feels so unresponsive and it's making me look for other software even though I like everything else about Lychee.

**Comment by electerious** [comment]
**Status update**

Preloading has been implemented for a while now. There're only two related issues left:
- https://github.com/electerious/Lychee/issues/361
- https://github.com/electerious/Lychee/issues/572

I will close this issue as it's no longer relevant.
