### ISSUE TITLE
[Feature] Select poster frame

### ISSUE THREAD

**Issue by chrismarquardt** [electerious/Lychee#193]
The only way that I found to make a picture be the main picture of an album that gets displayed in the albums overview is by starring it, but that kind of defeats the purpose of starring pictures. I would love to be able to specify an album's poster frame.

**Comment by HoffmannP** [comment]
could be a tag like `cover`, that would't be any extra effort but may be a dirty hack

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
