### ISSUE TITLE
Custom Smart Albums

### ISSUE THREAD

**Issue by chrismarquardt** [electerious/Lychee#197]
Sharing a link to an album or to an individual picture is simple enough. 

Would it be possible to extend this ease of sharing to searches?

**Comment by HoffmannP** [comment]
1+

**Comment by liljenstolpe** [comment]
++

**Comment by buechner** [comment]
1+

**Comment by crazikPL** [comment]
+1

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
