### ISSUE TITLE
Custom information per photo

### ISSUE THREAD

**Issue by chrismarquardt** [electerious/Lychee#199]
As a professional photographer, when I show my photography, I want visitors to be able to learn a bit more about me, link them to my blog or my homepage.

I don't seem to have a way of doing that other than in the album and picture descriptions.

How about allowing a couple of simple (optional) text fields on the home page, one above and one below the album thumbs. Bonus: markdown encoding.

**Comment by CryssDOTnet** [comment]
:thumbsup:

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
