### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by crealx** [electerious/Lychee#207]
If you are interested, I can translate it into french.
A translation plugin would be great !

**Comment by birdkiwi** [comment]
+1. I can help you with russian translation

**Comment by roeme** [comment]
@electerious Looking at #245, have you yet decided on how you'd like to tackle this? I did a cursory browse through the v3 branch, but couldn't see anything in this regard. Reason I'm asking is that I'm unsure wether I should prep a PR.

**Comment by electerious** [comment]
The v3 branch doesn't include anything regarding multiple languages. It seems to be a very complex thing, as there's text which come directly from the API and text spread across multiple JS files. I need to do some cleanup and other stuff before starting with this.

**Comment by roeme** [comment]
:+1: No hurry for my instance. Better come up something robust and clean than rushing hacks that come with technical debt.

**Comment by CryssDOTnet** [comment]
I could do the German translation.

**Comment by pmichelazzo** [comment]
I can make the Brazilian Portuguese translation when the Lychee is ready.

**Comment by sabatesduran** [comment]
I can make the Catalan and Spanish translation.

**Comment by ThiloL** [comment]
Ja, ein deutsches UI wäre nicht schlecht. :-)

**Comment by roeme** [comment]
@electerious, how do you want (me) to proceed with this? Some comments on #207 woke me up, making me aware of PR #315. Seeing that v3 has been merged to master since, and #461 overlapping with PR #315, and the latter having some conflicts now, it looks like (minor) additional work is required to adapt @myfreeweb's work.

That - or creating new multi-lang code alltogether, whatever floats your boat - I'm willing to do (as stated earlier), and seeing that develop is currently only three commits ahead of master, it seems like a good time.

All others: please refrain from further "I can provide translation to language XXX" or "+1"/"like" comments. It doesn't add any value to the discussion. Subscribe to the thread instead and provide a PR when the code is ready.

**Comment by teatall** [comment]
I can help do the Chinese Translation. Just let me know if you need.
我可以帮忙做中文的翻译。需要的话，告诉我就可以了。

**Comment by srishag** [comment]
I can help with Hindi translation!

**Comment by QuoFata** [comment]
Internationalization : 
index.html : Done. (renamed index.php)
lychee.pot file created.
=================================
[Lychee.zip](https://github.com/electerious/Lychee/files/1261273/Lychee.zip)

**Comment by dee6600** [comment]
i can help with hindi , marathi (popular indian languages)

**Comment by dmitry-moskalets** [comment]
Ukrainian too.

**Comment by sannc** [comment]
I strongly second the i18n feature and can help with the German translation.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
