### ISSUE TITLE
Define upload folder

### ISSUE THREAD

**Issue by r1z1** [electerious/Lychee#240]
It should be nice to specify the folder that holds the photos. If we want to store the photos on an external hard drive how can we do that? Maybe i'm wrong but i have not found where i can configure the upload folder.

**Comment by calimou** [comment]
Related issue : #282

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
