### ISSUE TITLE
option to change album creation date

### ISSUE THREAD

**Issue by lustyffh** [electerious/Lychee#248]
Hi,

it's very neat and nice looking that we have album/photo creation underneath the name. However, it seems to be an issue if you upload your photos and, consequently create an album much later than the date when photos were takes. With this you would have different timestamps in the photos and album. This is especially important for albums that make up a single event. It would be very nice to be able to change album creation date. However, taking minimalistic approach to configuration I suggest to automatically match creation date of the album to the date of the starred photo.

I've also tried to change the date in the mysql but I was surprised to see that even the time/date stamps are coded(encrypted?) in some bizarre way.

**Comment by petebulley** [comment]
Was about to write a feature request but found this similar issue...

We often upload our photos in the month after they are taken when we get back from travels or find time, and I then tend to go and change the album date in the DB. This workflow is fine but not ideal and doesn't work for those who don't know how to make changes to the DB. For example, my parents in law use Lychee and have to phone me to change the album dates!

It would be really nice if there was a setting option for album date displayed to be taken from the earliest photo (EXIF) rather than album creation. I think most people if choosing a date would choose the month/year that they started their trip/event etc. rather than the end so it makes sense (to me, at least) to use the earliest photo.

Is this something that could be easily added?

Thanks

**Comment by electerious** [comment]
@petebulley Not that easy to implement. In the end it's hard to tell where the date comes from. It would also mean that we need to look for the earliest photo in the album each time you move or add photos. A manual way to change the date is way easier.

**Comment by degenaro** [comment]
How about an option to choose between "captured" and "uploaded" date for display on album and for sorting?  Or the ability to edit the "uploaded" date of each photo?  Either would work for me.

**Comment by petebulley** [comment]
Sounds like manual change would be easiest and is fine for this use case. Manual update would be great!

**Comment by degenaro** [comment]
I could live with ability to edit "uploaded" date, but would prefer to choose between "captured" and "uploaded".  And in fact I would think the default should be to use "captured" date.  From an end user perspective, choosing "captured" once for the album (or for the entire site for that matter) seems far easier than editing every photo's "uploaded" date.  And there may be some value in keeping the "uploaded" date instead of lying about it...though for me there would be close to none.

**Comment by petebulley** [comment]
Agree that from a user perspective it would be easier to have a global perspective. But from a development perspective, if easier to add functionality to change the date for each album (imagine just change for album not each photo since photos already utilise EXIF data so would show correct dates), I imagine that would solve the issue for most users.

**Comment by degenaro** [comment]
And what about sorting photos within albums?

**Comment by petebulley** [comment]
Perhaps I misunderstand but it is already possible to choose the method of sorting based on EXIF data...

![sorting](https://cloud.githubusercontent.com/assets/13861853/18348621/56585b38-75c4-11e6-964d-b24f28f430ae.png)

**Comment by degenaro** [comment]
Nice!  Did not notice that.

But the album date is the upload date not the taken date.  And the photo
used for the Albums page is always the first sorted photo, but I'd like to
chose which one represents the album.

**Comment by petebulley** [comment]
I might be wrong but I think if you star a particular photo in the album it becomes the cover - at least thats how we do it

**Comment by degenaro** [comment]
Works!  So my sole complaint is reduced to wanting the album date to be the
taken date of the starred photo or some other "manual" date, but not
necessarily the uploaded date.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
