### ISSUE TITLE
API for third party programs 

### ISSUE THREAD

**Issue by lamarios** [electerious/Lychee#255]
Hi !

First of all thanks for your work, it is pretty good ! 

I was wondering if an API for third part programs was in the pipe ? If not, is it possible to get one to be able to work on native applications based on a lychee installation. That would be great.

Thanks !

**Comment by Akronix** [comment]
Hi! any news on this? @lamarios did you could connect a third-party application with the Lychee backend?
We are looking a way to upload pictures from a desktop app to the lychee albums.

**Comment by lamarios** [comment]
I did do it many moons ago, I’ll try to see if I can get back the source code, but it was for old versions it might not be applicable for newer versions anymore. 

The way I did it was to go through lychee’s front end code and figure out what end point it was calling.

**Comment by lamarios** [comment]
There you go:
https://gist.github.com/lamarios/df090d40d589ed8abf2bce3a5e1c755f

I'm not sure if it's still valid.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
