### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by TheZoker** [electerious/Lychee#266]
Hi there,

I have some png files with no background and black color on it and they look very bad:
![img_2014 11 20_22h48m14s_001_](https://cloud.githubusercontent.com/assets/1368405/5133887/32ea2bf2-7109-11e4-8bf6-b7f74bfd916f.png)

Can you please use something like photoshop:
http://multimedia.3m.com/mws/media/778065P/transparent-graphic-film.jpg

Thank you

**Comment by nguyen-matthias** [comment]
i have black thumbnails too... the picture had a resolution of 2592x1458 and the size 1.3 can some one help me ?

**Comment by electerious** [comment]
What's the content of your photo? This issue is about png files with no background and black color on it. The thumb of them isn't black, it's just transparent and Lychee shows them on a black background.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
