### ISSUE TITLE
Replace image

### ISSUE THREAD

**Issue by TheZoker** [electerious/Lychee#268]
Could you add a feature to replace a image?

I often use images on different pages and when I want to update them, I have to replace it with the new  direct link.

So I want to just replace the image, so the link stays the same, but the file it self changes.

Thank you

**Comment by VictorLamoine** [comment]
:+1:  for this feature, that would be useful.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
