### ISSUE TITLE
Use photo's stored elsewhere on the system

### ISSUE THREAD

**Issue by ervee** [electerious/Lychee#280]
Hi,

Not really a bug report, but a feature request as you will.

I stumbled upon your beautiful and easy-to-use Photo-Management-System and together with @GustavePate his lycheesync plugin I thought to have finally found _the_ gallery software I was looking for. But Gustave's plugin seems to be copying my local photo folder to Lychee instead if "indexing" it and using the local photo folder as source to serve the original photo.

Is it possible with Lychee to use an existing photo repository (like /data/photos/*) and "Index" that folder structure into Lychee? Not modifying the original repo in the process, storing generated thumbnails etc. inside the Lychee directory and/or Database.

Making that possible would in my opinion be super useful and the only Photo-Management-System in the world capable of doing that.

Ralf.

**Comment by electerious** [comment]
Hi, I really like the idea and this has been discussed very often, but Lychee needs it's own structure. Changing this would require a lot of adjustments and would not work with existing installations. It's a decision which should have been done different before starting with the project. More here: https://github.com/electerious/Lychee/issues/233

What would be possible: Storing Lychee's structure in a different folder (but I guess that's not what you want)

**Comment by ervee** [comment]
Hi, thank you for your time answering my question. StoringLychee in a different location is indeed not what I need.

I'll just keep on searching or learn programming. But I'm not putting my money on the latter :-( 

Thanks, Ralf.

**Comment by kworm1** [comment]
Hi, I would like to second this request. I have spent a lot of time looking for a good (and good looking!) photo management system, and lychee looks perfect, except that it is not possible to have it move my several terabytes of picture into its own folder.

I understand that based on the way Lychee is designed it needs its own file structure, but could I perhaps suggest to make it possible to "import and link" instead of "import and move". I.e. that Lychee creates a symlink to the files instead of moving them after import.?

Thanks, Kj

**Comment by GustavePate** [comment]
Hi kworm,

You could use lycheesync to symlink your photos in lychee's directory
structure.

Hope this help,

Gustave
