### ISSUE TITLE
Selectable Creative Commons license

### ISSUE THREAD

**Issue by PeterTheOne** [electerious/Lychee#287]
Make it possible to select a Creative Commons license (maybe per gallery) and display that license in the about section. http://creativecommons.org/

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
