### ISSUE TITLE
Feature Request: Facebook and Meta

### ISSUE THREAD

**Issue by cpzengel** [electerious/Lychee#294]
![bildschirmfoto 2015-01-20 um 16 06 18](https://cloud.githubusercontent.com/assets/7737962/5819507/bafd36b2-a0be-11e4-93fd-e662e3a32ad6.png)
Hi,

please can you add feature to have better facebook link abilities and meta information by gui?
hope this is the right place to do

tx
chriz

**Comment by electerious** [comment]
The problem is that all data gets loaded via AJAX and Facebook doesn't care about it. It isn't possible with the way Lychee works. This StackOverflow answer explains the problem: http://stackoverflow.com/questions/5167759/trying-to-update-facebook-open-graph-meta-tags-using-client-side-jquery-and-ajax 

The sharing works much better for single photos. Those are served using a php-file which includes the meta-data. Try sharing this link: http://l.electerious.com/view.php?p=13782040411088

![sharing](https://cloud.githubusercontent.com/assets/499088/5844051/439812d8-a1b1-11e4-9778-f04e06366047.png)
