### ISSUE TITLE
Importing tags from Adobe Bridge?

### ISSUE THREAD

**Issue by nehuen** [electerious/Lychee#309]
Hi! I've recently discovered Lychee and plan to use it in my daily workflow.
Right now, I'm using Adobe Bridge to organize and tag all my photographs, in order to have a well-sorted and searchable catalog. My intention is to replace Bridge with Lychee because of its flexibility and online features. The problem comes when importing some of the (Bridge) pre-tagged images to Lychee: those previous tags are not imported. I can see all the other information such as camera model, ISO, etc. but the "tags" field is empty.

![Image tags]
(https://dl.dropboxusercontent.com/u/2222475/img_tags.jpg)

Is there any way I can import all the tagging work I've done to Lychee and avoid retagging everything manually?

Thanks a lot!

**Comment by electerious** [comment]
I could add support for existing tags. They are separated by ";", right? Do you know if this separator is standardized for tags in metadata? I'm not sure how other apps are saving them in photos. What happens when you use ";" inside a tag?

Note: Data edited in Lychee won't be synced back to the files. Be sure that this isn't a problem for you when switching to Lychee.

**Comment by nehuen** [comment]
Exactly, tags created in Adobe Bridge are separated by semi-colon " ; ". 
I've done some research. Apparently, Adobe has standardized metadata through [XMP](http://www.adobe.com/products/xmp.html) platform. Apps such as Photoshop and Lightroom use this format.


https://dl.dropboxusercontent.com/u/2222475/tag_bridge.jpg
Since your comment, I've tried several approaches with colon: 1) forcing their use in Bridge and 2) inserting them manually in the file details (in order to check if they show up in Lychee). It didn't work. In addition, I tried adding semi-colon in Lychee but they are placed inside the tag:

(https://dl.dropboxusercontent.com/u/2222475/lychee_tags2.jpg)

**Comment by electerious** [comment]
Good to know! I think it would make sense to use semicolons in a later version. Lychee currently uses commas. The way of tagging photos should be improved, too.

Could you attach some tagged photos for testing?

**Comment by nehuen** [comment]
Sure! Here you go!


**BuenosAires_Planetario.jpg**
[https://dl.dropboxusercontent.com/u/2222475/BuenosAires_Planetario.jpg](https://dl.dropboxusercontent.com/u/2222475/BuenosAires_Planetario.jpg)
**Tags:** Palermo; Planetario; Verde

**BuenosAires_Obelisco.jpg**
[https://dl.dropboxusercontent.com/u/2222475/BuenosAires_Obelisco.jpg](https://dl.dropboxusercontent.com/u/2222475/BuenosAires_Obelisco.jpg)
**Tags:** Microcentro; Obelisco

**BuenosAires_LaBoca.jpg**
[https://dl.dropboxusercontent.com/u/2222475/BuenosAires_LaBoca.jpg](https://dl.dropboxusercontent.com/u/2222475/BuenosAires_LaBoca.jpg)
**Tags:** La Boca; Riachuelo

**Comment by bjoerns1983** [comment]
Btw is there any list which Tags, or out of which program, Tag are supported by Lychee?
I would like to have Lychee as Backend on my NAS for my Foto Collection. So it would be interesting for me that if i for example Tag Images with Tool XY, these Tags are supported by Lychee.

Or is there some kind of standard for Tags?

**Comment by electerious** [comment]
The current version of Lychee doesn't support Tags in photos. Tags are only added/removed from the database, not from the photo metadata itself. There's also no import of the embedded tags.

I'm not aware of a standard for Tags.

**Comment by Kernald** [comment]
I just checked on Digikam, tags are also semi-colon separated. I couldn't find any reference, but I think this can be seen as an implicit standard.

**Comment by electerious** [comment]
Thanks for the notice! I think we are save when we separate tags with semicolons.

Here's the code which handles the EXIF import: https://github.com/electerious/Lychee/blob/master/php/modules/Photo.php#L742 Help is appreciated. I'm open for a PR which adds a `$return['tags']` to the `getInfo(…)` function. Will do the rest.

**Comment by layanto** [comment]
I use F-Stop Android app for tagging photos taken on phone and I believe F-Stop stores the tag information in the photo file itself. Will confirm whether it is using ; or , as separator. For file formats that do not support storing tag metadata in the file, F-Stop is using sidecar.XML - seehttps://en.m.wikipedia.org/wiki/Sidecar_file

**Comment by sdenaro** [comment]
I'm having the exact same issue with IPTC and EXIF tags from lightroom. They aren't being imported.

The IPTC titles show up, which is nice. 

What I would really like is to use tags as albums so I wouldn't need to manually sort into albums. Having an option to make a tag an album would mean I could just export photos and re-use the tags from my workflow to sort my photos.

**Comment by electerious** [comment]
@sdenaro Custom SmartAlbums (#197) could be used for something like "Tags as albums". Nice idea :) I will keep that in mind.

**Comment by cavellblood** [comment]
Curious if **Importing tags from Adobe Bridge** is still a planned feature for Lychee and when it might be available. If you still need help I can see what I can do to help.

**Comment by cavellblood** [comment]
Don't know if this is the best implementation of it but here's what I was able to do and **this worked to import existing tags from the image**. I added this code after line `209` in `php/modules/Photo.php`

	208			# Read infos
	209			$info = $this->getInfo($path);
	210			
	211		# Begin new code
	212			$iptcArray	= array();
	213			$tagInfo	= getimagesize($path, $iptcArray);
	214			
	215			if(isset($iptcArray['APP13'])) {
	216				$iptcInfo = iptcparse($iptcArray['APP13']);
	217				if (is_array($iptcInfo)) {
	218					$temp = @$iptcInfo['2#025'];
	219					if (isset($temp)&& count($temp)>0) $tagArray = $temp;
	220				}
	221			}
	222			
	223			$tagCount	= 0;
	224			
	225			foreach ($tagArray as $tag) {
	226				if ($tagCount == 0) {
	227					$tags = $tag;
	228			} else {
	229					$tags .= ", ". $tag;
	230				}
	231				$tagCount++;
	232			}
	233		# End new code
	234
	235			# Use title of file if IPTC title missing
	236			if ($info['title']==='') $info['title'] = substr(basename($file['name'], $extension), 0, 30);

The above is getting the keywords from an array and adding them to the `$tags` variable separated by a comma. The keywords can have spaces in them as well. Haven't checked if they can have commas or semicolons in them yet though but this worked for me.

**Comment by electerious** [comment]
@cavellblood There's a [dedicated function](https://github.com/electerious/Lychee/blob/master/php/modules/Photo.php#L741) for getting information out of a photo. It should return the tags `$return['tags']`, seperated by comma, but without spaces (`$tags .= ",". $tag;` instead of `$tags .= ", ". $tag;`). Feel free to open a PR into the `develop` branch.

**Comment by cavellblood** [comment]
@electerious Yes, I saw that you had mentioned that earlier in this thread. It was this code that I used as a starting point to make what I did in my previous post. I've updated the previous code that I posted to remove the space after the comma.

It appeared to me that the the [dedicated function for getting information out of the photo](https://github.com/electerious/Lychee/blob/master/php/modules/Photo.php#L741) didn't add the tags to the database. But I do agree that if we add the `$return['tags']` to that function it could read existing tags/keywords from the image.

The reason why I put the code where I did is because I wanted the tags to be added to the database when the image is imported. Then I can search my images for certain tags. I don't believe that I can search for tags within the images if they are not in the database. Otherwise it would have to search every image every time I made a search.

Once the tags were added to the database they automatically showed up in the image information panel and they were searchable. And I think this is what @nehuen mentioned something about in [the first post on this thread](https://github.com/electerious/Lychee/issues/309#issue-58797132).

To me it looks like the tags need to be added to the database to be searchable. Is there a better way to get the tags into the database? And are tags only searchable if they are in the database?

**Comment by electerious** [comment]
@cavellblood The function won't add the tags directly to the database, but you can use the [response inside the add function](https://github.com/electerious/Lychee/blob/master/php/modules/Photo.php#L209) to add it to the database. Feel free to open a PR based on the develop-branch which just includes the `$return['tags']`. I can add the rest.

**Comment by electerious** [comment]
The next version of Lychee imports tags. Thanks to @qligier for implementing this feature. https://github.com/electerious/Lychee/pull/518
