### ISSUE TITLE
Allow user to set individual photos as private within a public album

### ISSUE THREAD

**Issue by halseyhemingway** [electerious/Lychee#313]
(disclaimer: I'm a bit new to github so if this belongs somewhere else let me know)

Basically I think it would be extremely helpful if there was a way to switch individual photos to private within an album that is public. Example use case: want to show most of my vacation photos but not the ones that are family shots, etc.

![screen shot 2015-03-14 at 8 15 52 pm](https://cloud.githubusercontent.com/assets/3520624/6654138/46c51db2-ca87-11e4-85c5-e697796b90ff.png)

**Comment by electerious** [comment]
This sounds like a great feature, but I'm wondering what would be the easiest way to implement this. A complex selection could be confusing. How about a "Exclude photos: "

**Comment by halseyhemingway** [comment]
I like the tags idea as well!

**Comment by roeme** [comment]
This might conceptually overlap with #254.

**Comment by liljenstolpe** [comment]
I like the tag-based idea as well.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
