### ISSUE TITLE
Photospheres / Panorama

### ISSUE THREAD

**Issue by BenoitDuffez** [electerious/Lychee#324]
_On a side note: I'm highly impressed by this app, congrats!!!_

I was wondering if a panorama / photosphere viewer would make it into Lychee?
I've been doing some using my Android device, and others with my DSLR (stitched using Hugin).
When uploaded to Google+ they have a nice sphere viewer. But the point of Lychee is to have some free and open source software, so I'd rather not use Google+.

I found these, I was wondering if they would be suitable with Lychee?
- https://github.com/kennydude/photosphere
- http://krpano.com/krpano.html?xml=tours/corfu/tour.xml&html5=only

The latter isn't free however.

**Comment by electerious** [comment]
I like the idea, but I don’t think I will have the time to implement this. A lot of other features are currently waiting. I will leave the issue open, maybe someone else can built it into Lychee.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
