### ISSUE TITLE
[Feature] Upload via drag and drop

### ISSUE THREAD

**Issue by thomas-mc-work** [electerious/Lychee#326]
Upload pictures into albums via drag and drop, even with whole folders. When dropping into the start page then prompt to create a new album.

**Comment by electerious** [comment]
You can already drag and drop photos, but adding support for folders is a good idea.

**Comment by xxcram** [comment]
Tweak the interface a little bit, so the user can see that import by drag and drop is possible.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
