### ISSUE TITLE
[Feature Request] Keep files where they are on server

### ISSUE THREAD

**Issue by danmandle** [electerious/Lychee#349]
This is a great project, but I manage my photos in Lightroom and store them on my NAS. It would be awesome if instead of copying the photos from the source directory into the Lychee upload directory it would leave the photos where they are and just reference them.

I understand thumbnail images need to be made and those could be in the Lychee file structure, but the full size images should stay where they are.

**Comment by electerious** [comment]
This feature is not planned for the following reasons:
- Would only work with "Import from Server"
- Renaming or moving the original file will break the photo in Lychee
- Rights need to be set correctly for all the referenced files/folders (often not the case)

**Comment by michael-stevenson** [comment]
Hey @electerious, as @danmandle said, cool project.  I just stumbled upon it myself and am trying to determine if it works for me..  That being said - @danmandle's request is exactly what I think I need to be able to use Lychee.  So, let me try to convince you..

* Would only work with "import from server" - so what?
* Renaming or moving the original file ... -> Why not just hard link?  A little bit of extra space for FS metadata, but otherwise, no harm, no foul.
* Rights need to be set correctly... -> With good error reporting, that seems like a non-issue, certainly one that I would be willing to deal with to have the requested functionality.

So?

**Comment by Enoch247** [comment]
As nice as this feature would be. I agree that it would cause a lot complications in knowing when to re-generate thumbnail and the medium images among other issues. At first, I wished such a feature existed, but in my case, I have plenty of hard drive space, and not a lot else to be gained by the feature. What would probably be more useful, is a CLI interface to Lychee so that I could import photos that are stored elsewhere (ownlcoud in my case) into Lychee automatically and not worry about the data being duplicated. There is a 3rd party CLI (lycheesync) which works nicely, but I don't think it has been updated to work with Lychee 3.0 yet.

**Comment by danmandle** [comment]
That would work for me as well. If every so often I could fire off a script that would import all of my photos and, I don't know, maybe check file size and location against a database, that'd be great.

**Comment by Enoch247** [comment]
Take a look at inotifywait. I use it with a while loop in a bash script (it blocks the loop until files are changed). It's a little more elegant than a cron job, and more responsive. If you are wiling to update lycheesync or use Lyche 2.x you should be in business.

https://github.com/GustavePate/lycheesync
http://linux.die.net/man/1/inotifywait

**Comment by danmandle** [comment]
I'm not looking for something to update that quickly, just when I occasionally add new photos. I'm slammed for the next few weeks, but I might take a stab at writing something to do this.

Is the API documented anywhere?

**Comment by electerious** [comment]
I guess that the best way to sync Lychee with a directory is a script like [lycheesync](https://github.com/GustavePate/lycheesync). It's currently not ready for Lychee v3, but I'm sure that @GustavePate is open for PRs. Alternative solutions and scripts are welcome. Lots of people are asking for plugins like this.

@danmandle Sorry, the API isn't documented, yet.

**Comment by GustavePate** [comment]
Wow Tobias, your fast ! I didn't see the 3.0 coming.
Luckily, I will have time to work on it next week.

**Comment by GustavePate** [comment]
Indeed lycheesync was totally ready for Lychee v3 ;)
Just tested it, works like a charm on Lychee v3.0.1 without having to code anything.

**Comment by Enoch247** [comment]
Interesting it did not work for me when I upgraded to v3.0.0. Something about an error with JSON as I recall, but maybe I have an out of date copy of lycheesync or other gremlins at work. I will re-test when I get home.

Actually, I'm wondering now if I had a blond moment and was passing Lychee's config file into lycheesync as the third arg rather than lycheesyncs config file....

**Comment by GustavePate** [comment]
By the way, 

@Enoch247

>lycheesync doesn't allowing you to make photos public

In the conf file, just add:

    "publicAlbum": 1

And lycheesync will create public albums instead of private :stuck_out_tongue_winking_eye:

**Comment by Enoch247** [comment]
Nice, I did not realize that. I guess I better go edit my config file...
