### ISSUE TITLE
upload from server represents security issue

### ISSUE THREAD

**Issue by Enoch247** [electerious/Lychee#351]
As I under stand the feature, the upload from server feature allows you to bypass any security measures other web apps such as owncloud, webdav, etc may have implemented. Since everything will be owned by the www user for most apps and the import feature allows you to enter a path relative to the entire file system, you could simply go searching for photos in other users folders such as "/var/www/owncloud/data/". This my not be a problem as Lychee is currently single user and most likely that user will be the root user for most servers, but I know some people have created multiple installations of Lychee on the same server to create a kind of multi-user environment. It would be trivial then to peek into other users Lychee install on the same server, and in doing so, also delete other user's photos.

**Comment by doekia** [comment]
It is the responsability of the sysadmin of a server to implement proper security settings.
Running ANY services as www-data user is nothing but a security hole.
If you ilmplement webdav service easy uploading you should ensure that the webdav system context matches SOLELY your lychee system context. Doing otherwise is not the reflect of lychee security breach but your system been - sorry no mean to offence - a stainer

**Comment by Enoch247** [comment]
There is a good chance I am doing something wrong, since I'm self taught, but I though that anything apache does (within the same vhost) has to all be run under the same uid/gid. While I agree that trusting web apps not to "mess" with each other's data is not an ideal security situation, I'm not sure that users will always have another option. Is there an industry accepted best practice for running multiple web apps or multiple instances of the same web app on the same host?

**Comment by doekia** [comment]
Module such as suexec for apache is usually what is used to isolate each user in his own context.
chroot is another alternative. More complex to deploy but even more secure
webdav module configuration has uid/gid part embedded
suphp alternative for php module
...
there is no one fits all mechanism. It depends on the needs and the kind of apps.

**Comment by electerious** [comment]
I agree with both for you. It's the responsibility of the sysadmin, but web-apps should do their best to avoid problems and insecure operations.

I'm not sure what's the best solution. There're a lot of users who want to import from different locations. It's a valid use-case. Adding an option to limit the import to the current Lychee folder won't work either: You need to be aware of the problem and activate the limitation by you own. In this case I assume that the user is also able to implement proper server security settings.

**Comment by LudovicRousseau** [comment]
Maybe I can describe how I use the "Import from server" feature.
* in the ``Lychee/uploads/import/`` folder I create a symbolic link to the folder containing the pictures
* I use the "Import from server" feature with the default path
* after the import I remove the symbolic link

Lychee can't modify the files it imports, they belong to another user. The apache server user ``www-data`` can only read the image files and copy them in Lychee internal storage.
Lychee can be restricted to only import from ``Lychee/uploads/import/`` and it will still work for me.
I also removed the write access to www-data in ``Lychee/uploads/import/`` so a hacked apache can't create a symbolic link to sensible files.

The problem is that Lychee complains with "Error: 'uploads/import' missing or not readable and writable (777 required)" even it is NOT required.

**Comment by electerious** [comment]
@LudovicRousseau It's almost impossible to explain everything in one sentence, that's why the error says that 777 is required even when it isn't (depending the installation). Here's how Lychee checks the rights: https://github.com/electerious/Lychee/blob/master/php/modules/misc.php#L150 Let me know what needs to be improved if the current implementation isn't working for you.

**Comment by LudovicRousseau** [comment]
@electerious in my use case the test ``is_writeable($path)`` is not needed because I don't need/want Lychee to remove the original images.

It is not problematic for me. Lychee works fine even with the "error" message.

**Comment by Enoch247** [comment]
Better wording for the error message might be to say insufficient read/write privileges and let the user decide how to make that happen. In my case, 777 is way too permissive (I have other services and shell access for several users) so I just give Lychee read/write access using group permissions.

@LudovicRousseau, you might consider recursively linking the images instead of linking the folder. I believe this would make Lychee happy as it could then remove the link and it would remove the need for you to do your third step. If hard links are an option you could use "cp -l" or you could try "cp -s" for symlinks, but "cp -s" has some restrictions. See below for a discussion of doing recursive symlinks using other methods:

http://unix.stackexchange.com/questions/159843/creating-symbolic-link-recursively

**Comment by electerious** [comment]
@Enoch247 Good idea. Just updated the error message to "Error: xxx is missing or has insufficient read/write privileges".

**Comment by JackFarrand** [comment]
What is the minimum permission level that will allow lychee to function?  It is not reasonable or good to set permissions to 777, and the minimum I could get to work is 667 which is almost as bad.  Why on earth does a data folder need execution permissions???

**Comment by Enoch247** [comment]
Execute bit means something different on folders than execute. It means the contents can be listed. It is common for folders to have this bit set and have a perission of say 755. In general as i remember (haven't played with lychee for some time) it needs read/write privileges to read each photo and then delete it when done. You can accomplish this a variety of ways with permission/group settings.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
