### ISSUE TITLE
Twitter Cards Not Working

### ISSUE THREAD

**Issue by evermorian** [electerious/Lychee#384]
When I place the URL for a Lychee image (e.g., http://photo.eurocafe.com/#6/14387524215889 ) into the Twitter Card Validator and, click the button, I get "Unable to render Card preview" in the Card Preview and "WARN:  Not whitelisted" in the Log. There is no "Request Approval" link or button. Is the Twitter Card functionality not working or, am I doing something wrong?

**Comment by evermorian** [comment]
Here's an updated "e.g." link: http://photo.eurocafe.com/#6/14387566174035
I upgraded to the latest version (which was NOT as easy as it should be and, resulted in restoring from a backup after it hosed itself, re-upgrading, re-sharing every gallery, then re-uploading the gallery with my example).
Upgrading to the very latest Lychee release made no difference in the Twitter Card behavior.

**Comment by electerious** [comment]
Twitter and Facebook require some special metatags in the head of the page. That's not possible when sharing images using a link to the webapp (`index.html`). Adding data to the head via AJAX has no impact. That's why the Twitter Cards feature only works when sharing an individual/single image (`view.php`).

WARNING: Just realized that the `view.php` is broken. I'm working on a fix. The following tutorial won't work for the moment.

**Sharing a single image with Twitter Card support:**
1. Open an image and make sure it's not within a public album
2. Click the eye on the top right and copy the share link
3. Make sure the link points to the `view.php`
4. Share the link on Twitter

**Sharing an image within an public album and Twitter Card support:**
1. Copy the image id (`http://photo.eurocafe.com/#6/14387566174035` => `14387566174035`)
2. Append the id to the following URL: `http://localhost/lychee/view.php?p=` => `http://localhost/lychee/view.php?p=14371258888581`
3. Share the link on Twitter

The documentation of the feature should be improved.

**Comment by electerious** [comment]
`view.php` has been fixed, but I still need to improve the Twitter Card documentation.

**Comment by electerious** [comment]
Sharing will be simplified in the next version. Just updated the my explanation. Sharing a photo now always shares the view.php-link.

**Comment by evermorian** [comment]
Awesome.  Thank you.  I used it successfully with your instructions here.
