### ISSUE TITLE
Non public photos are still accessibles via direct link

### ISSUE THREAD

**Issue by Kernald** [electerious/Lychee#391]
Photos which are not public are unavailable from share link (e.g. `view.php?p=14395043035752`), but are still available with the direct link (`uploads/big/885af8ddf9be37a4a992e9fb48ba7a77.jpg`).

**Comment by electerious** [comment]
The photos must be saved in a public directory in order to serve them. The server itself as no idea if you are logged in or not, or if the photo is public or private. I'm not aware of a good solution to block the direct access.

**Comment by Kernald** [comment]
What about storing the photos in a folder protected by an htaccess or something like that, and delivering them via a PHP wrapper checking that the user is authorized?

**Comment by electerious** [comment]
Possible, but extremely slow. Especially with PHP and for all those with a basic web-space.

**Comment by Strayer** [comment]
This is a typical usecase for [X-Sendfile](https://tn123.org/mod_xsendfile/) - this way the PHP process would only need to verify the access to the file, the actual transmission of the file itself is handled by the HTTP server. IIRC ownCloud uses this for sharing and I myself have used it in a lot of projects that need to serve large files (1GB+) with secure authentication. Its builtin in Nginx, but a little bit more complicated to configure. Apache should be pretty easy, but it requires the mentioned module.

**Comment by Manuel-Steinberg** [comment]
What do you think about a php internal routing?

Every request to "uploads/(.*)" will be redirected via .htaccess to a php-file, which checks the user privileges and return one of the following values (URLs):
* Blurred image for (returend and) non logged in users.
* The right picture for logged in users.

**Comment by electerious** [comment]
@Strayer Won't work on simple web-spaces, right?

@Manuel-Steinberg 

> […] return one of the following values (URLs):
> […]
> The right picture for logged in users

The photos still need to be accessible via direct link. Otherwise you will end in an infinite loop.

User logged in: Request to "uploads/big/a.jpg" =>  Redirect to php-file => Redirect to "uploads/big/a.jpg" => Redirect to php-file => …

**Comment by intheloft** [comment]
Not a re-direct but rewrite in .htaccess
I've only just started playing with Lychee but I like it so far, very neat.

You could implement it like so.

In the view.php page, load the image like <img src="imageloader.php?p=[IMAGE-ID]" />

Then in imageloader.php
$imageID = $_GET['p'];
//Check if user can view image
$allowed = check_permissions();
if($allowed)
{
//Display the image
$file = 'path/to/the/image.jpg';
$type = 'image/jpeg';
header('Content-Type:'.$type);
header('Content-Length: ' . filesize($file));
readfile($file);
}
else
{
//Display an error
$file = 'error/image.jpg';  //Just a basic image that says not found or such
$type = 'image/jpeg';
header('Content-Type:'.$type);
header('Content-Length: ' . filesize($file));
readfile($file);
}

Then block the uploads directory with .htaccess

Or, instead of using readfile, like Strayer said, mox_xsend would be better if the server supports it, maybe check if it's installed then fall back to readfile if not?

The photos do not need to be accessed via a direct link
There's no redirect loop here

**Comment by Strayer** [comment]
@intheloft The good thing about letting the webserver handle this is that it can react on HEAD requests and such. Also, the PHP process itself can't do anything else while transferring the file to the browser, thus effectively creating a bottleneck on high traffic installations.

@electerious I guess X-Sendfile won't work on shared webspaces, at least I don't think most would activate the module in case of Apache or would probably never allow direct access to the Nginx config.

In any case, X-Sendfile needs to be an optional function since the user would need to be able to configure a non-public upload directory and configure Apache/Nginx correctly to find this directory.
Its probably not trivial to implement this, but I thought at least suggesting it would make sense.

**Comment by Bramas** [comment]
I looked at how the other system works (like google photos, flickr, SmugMug...) and they all use public image url. This is considered sufficiently secured because not guessable urls act as a password ([http://www.theverge.com/2015/6/23/8830977/google-photos-security-public-url-privacy-protected](http://www.theverge.com/2015/6/23/8830977/google-photos-security-public-url-privacy-protected))

However, I also like the possibility of using X-Sendfile. A Plugin would be perfect!!

**Comment by alirz23** [comment]
Serving photos through php will cause significant performance overhead, the right question is how are the getting the hashed urls there is no way there guessing these hashes. have the directory listing disabled for that folder and you are good.

**Comment by Bramas** [comment]
I tried to write a plugin for this purpose: https://github.com/Bramas/lychee-webroot
It's called webroot because it become the public root of your lychee folder so that your photos and the all the php file are not directly accessible.
Photos are send either with the xsendfile directive (with nginx or apache) so that it does not have any overhead (expect the fact that it check for permission) or via php

**Comment by isntall** [comment]
This is a non-issue that should be closed.

**Comment by Bramas** [comment]
I agree

**Comment by electerious** [comment]
@Bramas Can I add lychee-webroot to the list of plugins/extensions?

**Comment by Bramas** [comment]
of course you can.

**Comment by electerious** [comment]
I'm closing this issue. Please take a closer look at @Bramas repository, which "Controls photos accessibility and keeps Lychee files hidden": https://github.com/Bramas/lychee-webroot

I'm still open for ideas. Please feel free to add further comments.
