### ISSUE TITLE
Autocompletion for tags

### ISSUE THREAD

**Issue by phsc84** [electerious/Lychee#397]
It would be great, if Lychee would offer auto-completing for tags when you type and/or show a list of all previously used tags. This would help to avoid chaos with your tags.

Use case:
You set the tag "weekend_in_italy" to some photos. A few days later, you want to tag some more photos with the same tag, but you cannot exactly remember the tag (did I use space or underline as word separator?). Then you have no possibility to find out the tag, when already tagging the photo.

**Comment by electerious** [comment]
Totally agree with you. Autocompletion for tags would be great.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
