### ISSUE TITLE
Tag in own table

### ISSUE THREAD

**Issue by HoffmannP** [electerious/Lychee#409]
I'd like to put the tags in their own table and hence add anoterh photo<->tag-table. That way autocompletion for example would be much simpler and searching for photos with a specific tag is possible without full text search.
I'd like to discuss this change bevor I start working on it.

**Comment by electerious** [comment]
Adding a new table for the tags is a good idea. I can add an update-script which converts all existing tags to the new format (When needed).

**Comment by electerious** [comment]
Suggestion by @qligier from #513:

> Tags should be in their own table, lychee_photo_tags, with columns photo_id (unsigned mediumint, index) and tag (varchar 30 should be enough). If so, column lychee_photos.tags should be dropped.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
