### ISSUE TITLE
Adding a 'cancel' button to the upload dialog

### ISSUE THREAD

**Issue by Tectu** [electerious/Lychee#439]
First of all let me say that I love Lychee. It's exactly what I wanted. Nice work!

Would it be possible to add a 'Cancel' button to the upload dialog? Ideally clicking this button would be followed by a 'are you sure?' dialog.

**Comment by electerious** [comment]
Nice addition, but with a very low priority.

**Comment by Tectu** [comment]
It is indeed. Thanks for your consideration! :)
And thanks for the great work - really.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
