### ISSUE TITLE
Save password in Safari and Firefox

### ISSUE THREAD

**Issue by Unresponsive** [electerious/Lychee#456]
My Lychee installation is one of the few pages where Safari (OS X) doesn't offer to save password. Have you labelled the input fields in some non-standard way so Safari doesn't treat them like username/password? I'm not sure what triggers Safari "save password?" dialog, but it would be very nice to save Lychee username/password and have it filled in automatically afterwards.

**Comment by Klikini** [comment]
The same happens (or doesn't actually!) in Chrome. It's because the login dialog does not contain a `<form>` that gets submitted (I'm assuming the login is handled via XHR instead).

Using `<form>` + `preventDefault()` may fix it.

**Comment by electerious** [comment]
@Klikini Thanks for the suggestion.

The problem exists since the first version of Lychee. I always thought it's because we're adding the login-dialog via JS. Fixing it would be a great thing. PRs or additional information are welcome!

**Comment by Klikini** [comment]
The above works fine in Chrome, but I could not test Firefox because it will not offer to save passwords regardless of anything in the page code if the site is running from localhost. I also don't have access to Safari, so it should probably be tested there before this is considered fixed.

**Comment by electerious** [comment]
Safari failed to show the login suggestions because Lychee filled in the username automatically. This has been removed and I successfully tested it with Chrome and Safari. I'm still not sure what triggers Safari "save password?" dialog, but we might try to use a <form> for the login window (as you already did in the PR. Just need to do some additional test as it hasn't worked for me).

**Comment by gsantner** [comment]
Firefox 49, Lychee 3.1.5 - can confirm this is still happening

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
