### ISSUE TITLE
Keep orirginal image

### ISSUE THREAD

**Issue by vitrex** [electerious/Lychee#460]
Hi,
great development so far!

I'm planning to use Lychee as a photo viewer, but it should also keep a backup of my photos. I would expect to get the original photo when using the 'Full Photo' button, but the files differ:

```
Original: 4,8M
Full Photo Download: 4,6M
```

Please keep an uncompressed copy of the uploaded photos (same md5sum), or make the compression of the big version configurable.

I am using c0c924fc13c3b675de06167a95fcbd803b0e4148

Thanks!

**Comment by electerious** [comment]
Lychee rotates the original photo when it's a jpeg containing a EXIF orientation. We need to do this to show the photo consistent across browsers. PHP removes the metadata in this step and there seems no easy way to keep them. You can install ImageMagick on your system which does a better job and only rotates the photo without recreating it.

**Comment by dun3** [comment]
Thank you for the great work! I am new to Lychee and I really love it.

If at all possible I would second this request. I need those files untouched. How about an additional "orig" dictionary in the uploads folder? Then I could mount a dedicated harddrive in the folder.

From my limited perspective (sorry, if I am too bold): Lychee could upload to "orig" then save the first converted version in the already established folder structure.

I also think that would be a first step to later support RAW much later on. Raw could end up in this "orig" folder and all further processing is done in JPEG form with the current folders.

Thanks again!

**Comment by qligier** [comment]
That could be an option in the settings, but not everyone wants to keep a copy of the original image (either because they have it in a photo library or because disk usage matters).

RAW images support could be added quite easily if imagick is available, DNG/NEF/NRW/CR2/RAW formats are supported (but not supported by GD).

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
