### ISSUE TITLE
Feature request: Files in another location

### ISSUE THREAD

**Issue by kworm1** [electerious/Lychee#468]
Hi, I know this has been asked for before, but the threads are closed and I would like to propose another solution.

I have spent a lot of time looking for a good (and good looking!) photo management system, and lychee looks perfect, except that it is not possible to have it move my several terabytes of picture into Lychee's own folder. 

I understand that based on the way Lychee is designed it needs its own file structure, but could I perhaps suggest to make it possible to "import and link" instead of "import and move". I.e. that Lychee creates a symlink to the files instead of moving them after import.?

Thanks, K

**Comment by electerious** [comment]
Lychee needs to rotate the original photo when it's a jpeg containing a EXIF orientation. We need to do this to show the photo consistent across browsers. Import and link isn't planned, because it adds a lot of new problems regarding incorrect permissions. You might want to take a look at [lycheesync](https://github.com/GustavePate/lycheesync) which a link mode. Could be exactly what you want :)

**Comment by dun3** [comment]
Thank you for the great work! I am new to Lychee and I really love it.

If at all possible I would second this request. I need those files untouched. How about an additional "orig" dictionary in the uploads folder? Then I could mount a dedicated harddrive in the folder. 

From my limited perspective (sorry, if I am too bold): Lychee could upload to "orig" then save the first converted version in the already established folder structure.

I also think that would be a first step to later support RAW much later on. Raw could end up in this "orig" folder and all further processing is done in JPEG form with the current folders.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
