### ISSUE TITLE
Feature request: Download search results

### ISSUE THREAD

**Issue by jkram** [electerious/Lychee#492]
When you search in Lychee, the results page that shows your pictures from the search does not have any option to download (unless I am missing something). I think a nice feature would allow you to download all the photos from a search, just like you can in an album view.

Very nice software, thank you for creating Lychee and for all of your efforts!

**Comment by electerious** [comment]
Thanks for the suggestion! Would make sense in combination with an improved [photo selection](https://github.com/electerious/Lychee/issues/339). Could be added as a right click option (Download selection).

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
