### ISSUE TITLE
Bad comportment on PHP session end

### ISSUE THREAD

**Issue by loclamor** [electerious/Lychee#510]
When php session expire, we are not logged off, and some server request show this error : "Error: Function not found! Please check the spelling of the called function."

**Comment by electerious** [comment]
Good point. That behavior should be improved, but it might not be that easy with the current front-end.

Best-case: Show the login window (again) and retry the current request.

Problems I can think of:
- Login modal closes current modal (if there's one open)
- We need to detect that the user has been logged out
- Request has to be saved/cached in order to retry it

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
