### ISSUE TITLE
Downloading album inefficiency?

### ISSUE THREAD

**Issue by Unresponsive** [electerious/Lychee#538]
When I click to downolad all images in an album (cloud icon), it seems Lychee zips them every time again and then downloads. If an album is several hundreds of MB, it takes significant time. 

Wouldn't it be better to reuse the prevoius .zip saved in /data?

**Comment by qligier** [comment]
The storage is important for some people, the CPU for others so none of them are the best option.

It takes time because it tries to compress the files. That's in fact useless because the final size is almost the same size as the JPGs (see [Why are the .zip files of compressed .jpegs about the same size?](http://askubuntu.com/questions/274117/why-are-the-zip-files-of-compressed-jpegs-about-the-same-size).
The files should only be stored in the ZIP, not compressed; it would be much faster. But this feature, [which has be requested in 2007](https://bugs.php.net/bug.php?id=41243), will only be available in PHP7. That would be the best option for everybody because it's fast and use no storage.

**Comment by electerious** [comment]
Depends on the images in the album. It might makes sense to compress them when the album contains GIFs and PNGs. But … I guess that most people use JPEGs. Turing off the compression would be an option to speed up the download start.

> Wouldn't it be better to reuse the prevoius .zip saved in /data?

Possible, but that would require to check if the album changed since the last zip generation.

**Comment by rsmith4321** [comment]
Do you have a way to turn off the compression?  My images are already compressed I would prefer the zip file be created just by combining the files similar to how owncloud does it without any compression.

**Comment by qligier** [comment]
Owncloud is [using the native ZIP library](https://github.com/owncloud/core/blob/master/lib/private/Archive/ZIP.php) so they also compress the images.

Following solutions exist:

- Using an external library, such as [PclZip](http://www.phpconcept.net/pclzip) (not updated since a long time)
- Creating ZIP file with bash command
- Creating TAR file instead of ZIP. Widely supported now but not really known.

**Comment by Unresponsive** [comment]
> The storage is important for some people, the CPU for others so none of them are the best option.

Well Lychee was doing the worst of both approaches – keeping the .zip on server (in /data) AND rezipping all files on every download request.

I have upgraded to the latest .1 release and seems that at least .zip is being deleted now? Is that a recent change?

**Comment by electerious** [comment]
@Unresponsive No changes have been made. Lychee [should delete](https://github.com/electerious/Lychee/blob/master/php/Modules/Album.php#L317) the files after processing the .zip. Maybe it failed because it had no permissions to delete the file.

**Comment by Unresponsive** [comment]
Or maybe I looked at the .zip file while it was still downloading.

Actually my main gripe is that the download starts with a huge delay when the .zip file is generated on demand (minutes if the album is big). By then most users have clicked several times thinking the download isn't working and closed the page. If not for this usability problem it wouldn't matter much which way it is done.

**Comment by UdoKifferbrehl** [comment]
I have got an album with about 200 photos and when I try to download all of them I always get a timeout. Downloading albums with less photos (I tried albums with 10 and 20 photos) are no problem. Can you help me please?

**Comment by bb-Ricardo** [comment]
did you check your PHP settings? Especially "max_execution_time"?

**Comment by jce** [comment]
I also have a problem with downloading large albums: I have set all parameters correctly, including execution time but the download still fails out of memory reasons. I have now set the memory limit to "-1" but then the browser itself (Chrome) seems to terminate the connection before the ZIP is created.

For reference: The final ZIP size is 1.5 GB...

How can I make this download possible?

**Comment by qligier** [comment]
The [PHPZip library](https://github.com/Grandt/PHPZip) allows to stream the archive while creating it, so it would be possible to create very large archives.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
