### ISSUE TITLE
Feature: Album sorting by timestamp

### ISSUE THREAD

**Issue by icehawk-de** [electerious/Lychee#539]
The album sorting is only by creation time (id), title, description and public.
I want to sort my albums by timestamp. I have edited the timespamp in the database.
I created two albums: January and March 2016. I created march first. I edited the timestamp of the two albums. 
Now the gallery shows: January 2016 -> March 2016 -> older. 
But I want to have: March 2016 -> January 2016 -> older.

Is this possible?

**Comment by icehawk-de** [comment]
Similar to closed issue: #477

**Comment by electerious** [comment]
Yes, a "Sort by timestamp" should be added when it's possible to edit the timestamp.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
