### ISSUE TITLE
view.php: Link to Album, Page ...

### ISSUE THREAD

**Issue by WulfmanGer** [electerious/Lychee#545]
When i shared a Picture in FB etc. it will use the view.php. User click this - see the picture ... and now? It is not possible to switch from this picture to home, album etc. view.php is a one-way-street.

**Comment by electerious** [comment]
A link to the main installation could be added to the header. I think that's a good idea.

**Comment by ryuuseki** [comment]
On the same train of thought, opengraph information is not supplied to facebook if the album URL is supplied. As is, sharing to FB isn't fully functional, since it's impossible for the user to navigate the rest of the album using the individual photo share link. Album links do not populate a thumbnail or proper title using facebook's own interface, and only supply the title using the sharing dialogue but no image.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
