### ISSUE TITLE
Metadata Stripping Causing Loss in Image Quality

### ISSUE THREAD

**Issue by dwmunster** [electerious/Lychee#564]
### Detailed description of the problem
After upgrading to 3.1.2, the thumbnails and medium quality images generated for new uploads have significantly different appearances from the original/big uploads. The difference is particularly noticeable in faces which seem very washed out compared to the original file.

Some research led me to #556 and its suggestions for reducing image size. Changing the quality to 100 did not remedy the issue, however, commenting out the stripImage calls did restore the original image quality.

### Steps to reproduce the issue
Upload an image with 3.1.2.

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.2
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50505
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1-dev
Plugins:         

### Browser and system
Google Chrome Version 51.0.2704.84 (64-bit)
OS X El Capitan (2015 Macbook Air 13")

**Comment by qligier** [comment]
The color change is caused by the deletion of an included color profile. You've exported your photos with a special ICC profile, what isn't particularly recommended (unless you've a good reason to do so). For the web, it's best to use an sRGB profile and don't include it in the JPG files; they will be smaller.
http://www.dpbestflow.org/color/color-management-overview
https://imageoptim.com/color-profiles.html

**Comment by electerious** [comment]
Yes, colors of thumbnails might be a little different compared to those with metatdata. I recommend to remove the metadata stripping when it's a problem, but most users will benefit from it (smaller file-sizes, fast loading).
