### ISSUE TITLE
feature/subalbums cannon start with error "Missing parameters. Can not execute function Lychee\Access\Admin::getAlbumsAction"

### ISSUE THREAD

**Issue by Rurik19** [electerious/Lychee#595]
### Detailed description of the problem

after setup  parameters, there is blank screen  with error in console

Missing parameters. Can not execute function Lychee\Access\Admin::getAlbumsAction

**Comment by electerious** [comment]
@hrniels Could you take a look at it?

**Comment by hrniels** [comment]
My guess is that the database update wasn't performed, so that the query failed.
@Rurik19 Could you show the end of the log? There should be an entry about the failed query. (You can either look in the database directly or checkout a different branch so that Lychee loads again.)

**Comment by Rurik19** [comment]
**@hrniels** You right about database errors are:
- Lychee\Modules\Database::createTables   Table 'lychee2.lychee_settings' doesn't exist
-  Lychee\Modules\Database::createTables  Table 'lychee2.lychee_albums' doesn't exist
-  Lychee\Modules\Database::createTables  Table 'lychee2.lychee_photos' doesn't exist
-  update_030103  Unknown column 'parent' in 'field list'

I've created new mysql database, new user with all privileges.

**Comment by Rurik19** [comment]
tables  'lychee2.lychee_settings' ,   'lychee2.lychee_albums',  'lychee2.lychee_photos' exist, but last two without any fields

**Comment by hrniels** [comment]
Okay, that looks good. These errors are expected, because they origin from test queries.

Have you rebuilt the frontend files? dist/* is not up to date in the feature/subalbums branch. You need to go into the src directory and run `npm run compile` to regenerate the files in dist. Please look into docs/Build.md for details.

**Comment by Rurik19** [comment]
Yes, rebuild dist helps. Thanks!

**Comment by jhice** [comment]
Hi there,

I'm trying to install the subalbum branch and face the same problem.
I tried to rebuild the file but I've got some errors, perhaps because I dont know anything about building (I have npm and node installed like said in the docs).

Here's the log : [npm-report.txt](https://github.com/electerious/Lychee/files/533985/npm-report.txt)

Help welcomed.
Thanks.

**Comment by electerious** [comment]
@jhice This PR now includes everything you need to test the new feature: https://github.com/electerious/Lychee/pull/639
