### ISSUE TITLE
How to set a max size file for images in uploads/big directory?

### ISSUE THREAD

**Issue by LiliwoL** [electerious/Lychee#617]
Hi,
i've set a large amount of pictures in **uploads/import**.
These pictures are straight right from camera, so they are around 6 or 8Mb.

I import them to an album (it's very long and there is no way to know when it'll be finished or which file is currently in work, that's a bad thing), and then, these files are stored in **uploads/big** dir.

I'm using mogrify to decrease their size to max 3Mb, but is there a way to set it up in a config file?

Here is the command i use in **uploads/big** dir after importing:
`find -iname "*.jpg" -type f -print0 | parallel --progress -0 -j +0 "mogrify -resize 2000000\> {}"`

So my asks / thoughts:
- add a display to tell user which file is currenlty in work when importing mass files
- set a max file size to store in big directory.

Thanks a lot.
N.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
