### ISSUE TITLE
Image zooming/panning

### ISSUE THREAD

**Issue by iownall555** [electerious/Lychee#619]
I was wondering if image zooming and panning was planned at some point. I've noticed there is no way (as far as I'm aware) to zoom in on an image that is too wide or too tall without using the "Full Photo" option in the menu.

As far as the implementation goes, the buttons could sit on the menu bar or the image could be zoomed with the scroll wheel and panned by clicking and dragging.

This would be extremely useful for users who are viewing large images on small screens such as those found on small laptops, phones and tablets and do want to open the full image every time.

**Comment by electerious** [comment]
Good point. That would be a nice improvement for big photos, too!

**Comment by TheHLee** [comment]
I'm definitely very interested in this one as well. The auto static sizing for the preview image is often too small, depending on the orientation of my phone. Having the ability to pinch zoom in / out would help alleviate that.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
