### ISSUE TITLE
Selecting images in small albums

### ISSUE THREAD

**Issue by akjackson1** [electerious/Lychee#621]
Dragging to select images does not work when there are only a few rows of pictures in an album, which results in `div.content` not extending to the full height of the page, and the cursor is clicked below `div.content`. I fiddled a bit and wasn't able to find an easy fix, so maybe it's a fairly involved bug.

**Comment by electerious** [comment]
Good point. Thanks for letting me know!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
