### ISSUE TITLE
Mouse flickers

### ISSUE THREAD

**Issue by bjtaylor1** [electerious/Lychee#623]
When I move the mouse it annoyingly flickers between full screen and not.

I notice it doesn't do this on the live demo, that uses mouseenter and mousemove to control full screen operation rather than mousemove, which I think is much better.

So what I've done on my own installation and what I propose changing is replacing the mousemove event with

``` javascript
// Fullscreen
$(document).bind("mouseenter", header.show).bind("mouseleave", header.hide);
```

However on my own installation I have had to manually copy and paste this into dist/main.js as I can't get gulp to work (which I presume is the thing that minifies the JS?) - https://github.com/electerious/Lychee/issues/622

main/dist.js: https://github.com/bjtaylor1/Lychee/commit/18e54896e85bdde61485449c7c2b35ecf4eaf8e2
src/scripts/view.js: https://github.com/bjtaylor1/Lychee/commit/86368b03f3d4c3775de9e049813fab1216c8ad50

**Comment by electerious** [comment]
We used `mouseenter` and `mouseleave` in old versions. `mousemove` could cause more problems, but I'm not sure why the mouse should flicker because of this. What browser and system are you using? Could you attach a video of the problem? Does it depend on how fast your mouse moves?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
