### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by justinkelly** [electerious/Lychee#63]
Hi Electerious

Lychee looks exactly what i need but..

I'd love to be able to upload and display videos just as they were photos

with google plus - in the one album i may have a few photos and a videos all relating to the same thing

Even though it may be abit off from your original aim I think it would be a great addition

Cheers

Justin

**Comment by CarlAmbroselli** [comment]
I think a year later the browser support changed a lot. Are there any plans on integrating videos?

**Comment by electerious** [comment]
Yes, things changed a lot. I think it should be possible now, but there are other features on the roadmap, so I can't give this one a high priority.

Ideas for the implementation are welcome!

**Comment by birdkiwi** [comment]
+1

**Comment by salyh** [comment]
+1 (+willing to donate money for this)

**Comment by NoodleBB** [comment]
+1 :+1: It's the only reason, why my wife prefers iCloud. :cry:

**Comment by rhurling** [comment]
My idea for an implementation would be something like this:

- Use http://mediaelementjs.com/
- If file not supported (for example avi) allow download
- Allow selecting of thumbnail from other photos in album

I'll see if I can figure that out and if I'll make a PR against the v3 branch

**Comment by Jonathan34** [comment]
Hope videos support will be implemented soon :+1:

**Comment by helli72** [comment]
Also like to have videos  soon :+1:

**Comment by UdoKifferbrehl** [comment]
Any updates?

**Comment by basco** [comment]
using lychee for one week, it's great.
videos would be awsome.
please also ass MTS container support while you're at it. thanks.

**Comment by JoeHana** [comment]
Will start using it now as it seems to be the best looking software for my needs - but yes, Video Support would be awesome since I too have many videos (like many others here).

Looking forward to it :) Keep up the good work. Let me know if there is anything to do.

**Comment by westframe** [comment]
Same here. I'm happy to invest for a video plugin. Let me know where to start, and how to help.

**Comment by 4ever911** [comment]
same here, i also need video feature.

**Comment by birdkiwi** [comment]
Let's donate to this feature!

@electerious, how much it will take to make video upload possible? Without auto-thumbnails and meta-data.

MPEG-4/H.264 video format supported almost in all major browsers:
http://caniuse.com/#search=mp4

**Comment by frazei** [comment]
+1

**Comment by kapone** [comment]
I will also donate for video support! How much to get started? a few hundred?

**Comment by chasebolt** [comment]
+1 would love to have video support

**Comment by theAlchemist-dev** [comment]
If you could point me in the right direction, I could try to add video support?

I guess if 3 years pass without implementing it, it is not on your priority list?

**Comment by jaywilliams** [comment]
Videos are difficult to handle, especially in a completely self-hosted solution, such as Lychee. If someone *really* want's a feature like this, I'd suggest finding a good PHP developer, and paying them to create a plugin/fork with the video feature you desire.

But sufficient to say "adding video support" is not a trivial matter.

**Comment by theAlchemist-dev** [comment]
@jaywilliams 
What a strange reaction.
I am not saying that I want to `quickly` add video support.

I am a PHP dev myself and if I understand that it could be a radical change to this project, but if it is in everyone's interest, I am willing to invest my time :)

**Comment by jaywilliams** [comment]
In that case, maybe you'd want to check out one of the existing pull-request (https://github.com/electerious/Lychee/pull/353) and continue on?

That's one of the wonderful things about open source software.

**Comment by ultramizer** [comment]
We still have a huge urge for this feature! I have found that if you replace the <img> tag that is as following:
`<img id=​"image" class src=​"uploads/​big/​test.mp4" srcset=​"uploads/​medium/​test.mp4 1920w, uploads/​big/​test.mp4 4000w" draggable=​"false">​`

With the <video> tag like this:
`<video id=​"image" class src=​"uploads/​big/​test.mp4" srcset=​"uploads/​medium/​test.mp4 1920w, uploads/​big/​test.mp4 4000w" draggable=​"false" controls></video>​`

It then works like a charm. There is no need for player controls, since every current browser does that. All you would have to upload is a h264 MP4 file, which can be read in every browser i tested. When uploading the file, you would just skip the conversion for medium or big completely, and just generate a thumbnail. This could be done easily with javascript, and even generating thumbnails would not be a big need as of right now for us. It would just be perfect if we could upload the MP4 files, and just somehow it should do a <video> tag instead of a <img> tag if it detects the file as a MP4 and not a JPG for example... For a developer thats working with PHP and some javascript, this should be a job of minutes, i have absolutely no experience writing the code... Maybe someone can do a quick writeup...

**Comment by helmut72** [comment]
Or switch to
http://piwigo.org

**Comment by ultramizer** [comment]
While Piwigo might seem as an alternative, i don‘t think this is an appropriate comment. I am trying to give productive feedback and possible solutions as good as i can with my little development knowledge, so proposing to switch to another tool is not really the way to go. This said, i really dislike the appear of Piwigo.

**Comment by helmut72** [comment]
Waiting 4 years is also not appropriate. Yes you're right regarding Piwigos appear in the past, but the new Bootstrap theme is a big step into the right direction:
https://pwgdemo.kuther.net

**Comment by ultramizer** [comment]
I have ofcourse not been waiting 4 years, i have found this tool after a ton of research just a few days ago, and evaluating how it works. Since it seems like the development pace is now beeing picked up by the community, maybe those are things that can be done. I understand that the original creator has stopped supporting and developing the tool, but this is offtopic. Your demo of piwigo looks nice.

**Comment by fly-man-** [comment]
@ultramizer The original creator hasn't stopped but he has given permissions to start a Organization so people that want to work on it can do it.

**Comment by matamn** [comment]
+1

**Comment by mickael-kerjean** [comment]
I've release a new version of [nuage](https://github.com/mickael-kerjean/nuage/wiki/Release-0.2:-Photo-Management) that's working nice with video

**Comment by mickael-kerjean** [comment]
> KISS - keep it simple s.....

The docker installer is [3 commands away](https://github.com/mickael-kerjean/nuage/wiki/Installation:-Selfhosting). If you want to play it hard, you can see how to make the install from [here](https://github.com/mickael-kerjean/nuage/blob/master/docker/Dockerfile) and [here](https://github.com/mickael-kerjean/nuage_transform/blob/master/docker/Dockerfile). If you're patient enough to make it work, the transcoding server (which handle the CPU heavy operation) will likely slow down the main application process. 

> unknown dependencies

like?

**Comment by helmut72** [comment]
> like?

Search for "Backdoored images downloaded 5 million times finally removed from Docker Hub". No Docker for security reasons. It must also work on a Raspberry. Next to other services on the same Raspberry.

> If you want to play it hard

Good warning. Looks like it's unmanageable from an early state. Now back to topic.

**Comment by mickael-kerjean** [comment]
@helmut72: I dont' want to pollute this issue as it's not directly related to Lychee but feel free to open an issue [here](https://github.com/mickael-kerjean/nuage/issues/new) and I'll adress those

**Comment by kelvinau** [comment]
+1 for video support

**Comment by hitam4450** [comment]
+2

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
