### ISSUE TITLE
Does "Import from server" delete the source files ?

### ISSUE THREAD

**Issue by ldanicel** [electerious/Lychee#638]
I'm trying to figure out what happened with one of my installations, does the import from server path modifies in any way the source photos ?

**Comment by electerious** [comment]
Yes, it deletes the original photos when the permissions allow it.

**Comment by ldanicel** [comment]
I'm not gonna die rolling on the floor crying now but you realize this is *bad* right ? 
**Especially** that the UI **does** **not** warn you about this in any way.
I'm currently recovering stuff up with photorec because of it :(

On a side note: You are taking already folder organized photos and dump them in one or several directories, also renaming all photos to their md5 hashes, while keeping the album/structure in a database.

Wasn't it way easier to just keep the original storing place and just create the album/structure in the db ? Why bother moving and renaming them ? I don't see the logic.

**Comment by ldanicel** [comment]
Not to mention the inconsistency of the actions where
*Import from Dropbox*
*Upload Photo* 
action wouldn't delete the originals ...

**Comment by electerious** [comment]
Sorry to hear :( There's actually a bold text in the dialog saying that it will delete the originals. But yes, I agree… it's not good to delete them. I remember the reason for this feature was that some weren't able to import photos because they were running out of storage. The storage problem was caused by all the temporary duplicates (original photos + imported photos). I personally think we should remove this "feature", again.

**Comment by qligier** [comment]
> Why bother moving and renaming them ?

The web-server cannot serve files located outside of its root directory, so moving the photos is needed.

**Comment by ldanicel** [comment]
There are ways to get around the webserver rootdir issue.
Right now ... copying them instead of moving them would've been just fine... and yes only now I've seen the "Warning" - I admit not reading it before as it was named ... *import*

**Comment by ldanicel** [comment]
Are the files moved  or copied and the source deleted?
Also, except the renaming is there anything else modified to them ?

**Comment by qligier** [comment]
> There are ways to get around the webserver rootdir issue.

Manually yes. But to automate this, we can only move/copy the files or create symlinks (that could actually be a good solution).

> Are the files moved or copied and the source deleted?

They [are copied and the originals deleted](https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L180-L186) (that is actually weird).

> Also, except the renaming is there anything else modified to them ?

They could [be rotated](https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L469) if the associated EXIF data exists. The original isn't resized and its metadata should be conserved.

**Comment by LudovicRousseau** [comment]
> we can only move/copy the files or create symlinks (that could actually be a good solution).

Using a hard link (instead of a symbolic link) would be even better. So the images in Lychee would still be present even if the original file is deleted.

That would work only if the original image and the Lychee image are in the same disk partition. So a fall back solution may still be needed.

**Comment by qligier** [comment]
Yes, using hard links could be better for many users that have only one partition and need another security against mistaken deletions. I would use symlinks nonetheless.

In fact I don't see any reason why we shouldn't use hard links for server import.

**Comment by ldanicel** [comment]
I honestly believe data should be either:
* imported as marketed - just copied - not deleted 
* maintained as it is already structured in folders and parsed. 
One should be able to softlink/hardlink it or just move the data in a custom-uploads directory inside the webroot...
But I guess for these 2 to work simultaneously there's some refactoring needed.

PS: If you leave the current import "feature" as it is please add another warning after you enter the path and push the import button. It would be lifesaving :)

**Comment by khenderick** [comment]
This hard-linking would actually make a lot of sense, especially with the [Lychee sync](GustavePate/lycheesync) plugin:
* No data duplication
* Original files stay where they are (leaving e.g. folder structure into place)
* No issues with removing a photo from lychee removing the originals
* With lychee sync, if the original files are removed from the original structure, they will be removed from lychee, so the user can keep on (partially) managing his photos with the original structure

**Comment by tessus** [comment]
Lychee is a great gallery, beatiful, and fast. Unfortunately its design is flawed which makes it useless for people who want to keep their file structure.

If I import the images from the server, they vanish and I can never find them on the server ever again. They are basically lost in a black box and if I ever wanted to transfer them to a new server, I couldn't.
Maybe I don't understand the reasoning behind the decision to rename the images and drop them all in a few directories, but imagine 50,000+ images in one folder.

Every gallery software should be a frontend for files on disk and not create its own file store. That's why you have a database: to reference and match the logical view to the physical data on disk.

**Comment by DeviantEng** [comment]
The thing that prevents me from using (and loving) Lychee is the fact that it is destructive.  Look at Lightroom, as an example.  You point it to a dir and it stores any changes in a db (albiet, sqlite), but is non-destructive to the actual image files.  Yes, I understand that the photos must live within the webserver root dir, and I agree links (sym or hard) would be a possible solution.  

I have 2 unique scenarios, that I'm sure a lot of people DON'T share with me.  The first is for my phone photos.  I have a LXC (Linux Container) running Nginx to serve webdav, and I use an app on my phone to sync all photos to that webdav share which resides inside my userdrive on my storage server.  That userdrive is automounted via NFS to any Mac I log into on my LAN, so I can effectively (almost) instantly access phone photos from Finder on my Mac, which I love.  A step further would be to stack Lychee ontop there, so it could serve these same files via a webUI, without touching/modifying/renaming/moving the original file (if the original was renamed, my auto-backup would duplicate files).  I currently only have 6 folders in my `./Photos/Phones` dir, and my smaller folder contains ~125 photos, while the largest is over 1200.  I would like each folder to be created as a separate album.  Currently, I use Sigal (http://sigal.saimon.org/en/latest/), which is a static gallery generator, to do this.  But it lacks important features such as tagging, favoriting, notes, and a few other things that Lychee could do 10 times better.

My other scenario is with photos taken with a camera; be it my GoPro or my Olympus M5 mk II.  Those go in a different dir, and structured differently (`./Photos/Camera/<camera_model>/year/month/<album_name>/{RAW,EDIT}`) and I would love if Lychee could take any picture in that EDIT folder, and use `<album_name>` as a separate album.  That would make Lychee perfect for automation and just working, and super easy to share (give me album level permissions so my phone photos are only available to myself but other albums can be shared if I want).

Sorry for the long post, but I agree that Lychee being non-destructive would be ideal.

**Comment by tessus** [comment]
I really would like to underscore that the images **DO NOT** have to live in the web server root directory. As a matter of fact this (accessing raw files directly) is a rather discouraged approach.

The images have to be acessable by either the httpd user (PHP used as module) **or** the php user (PHP used as cgi or fpm).

**Comment by LudovicRousseau** [comment]
@DeviantEng, Lychee is destructive _only_ if the Unix account running the web server (www-data in my Debian system) can delete the files.

For example I upload my images under my own account. And then add a symbolic link from ``Lychee/uploads/import/`` to my images directory. The images are imported by Lychee and the originals are **not** touched.

Since you already have a complex setup I think that should be easy for you to add such a non-destructive support of Lychee.

**Comment by ldanicel** [comment]
I'm sorry to tell you but this sound horrible from the usability / human point of view.
It might make sense as a technical solution ( although I wouldn't vouch for that either ) but its complete non sense when you look at it from outside the box.
Unfortunately, a new user, technical or non technical, will look from outside the box when he's gonna try the product for the first time... and he's gonna end up deleting his data : - )

**Comment by zobra00** [comment]
I figured I'd chime in on this as well. I have a similar case to DeviantEng. My imports from many devices are managed by an import/renaming script that keep a human usable file structure.
(picturelib/sorted/yyyyQ[1-4]/yyyymmddhhmmss_cammodel_hash.jpg) ->human readable, searchable by OS find commands and duplicate proof.  
I don't want Lychee to touch my structure, and I obviously don't want to duplicate 50,000 pictures. 

I've tried Lycheesync, I find its EXIF capabilities are not as good as Lychee. Also I don't like the idea that it basically is doing all the work instead of Lychee, this is asking for trouble in the future.

I changed Lychee's photo.php to symlink instead of copy and unlink. This seems to work, but it still NEEDS write access to the actual pictures because of rotation, the import window hangs and php shows a fatal error because imagick can't write the rotated image. 
It does neatly create an album for every folder with the files in that folder. (prepending with [import] but thats easily changed)

I am not sure how to proceed now, I don't really want to give write access, but the only other option I see is having Lychee rotate images on the fly, which I don't think is a problem. Apart from a a bunch of code in several places, and my PHP is poor. 

As for linking, I prefer symlinks as they are more understandable to the end user.  And the main goal, at least to me, is for Lychee to mirror my library. I realize that it's not as easy just changing that one line of code, it needs a bit of work to speed up imports when only a few files have been added and to deal with (re)moved files. 

I've been trying to get a reliable system for a few years and have tried many WebUIs, but I keep coming back to Lychee hoping to make it work.

**Comment by DeviantEng** [comment]
@zobra00 
FWIW, I keep checking Lychee every couple of months hoping to see something that would let this be an ideal solution for me, but that still hasn't happened.  In the meantime, I've been using [Sigal](https://github.com/saimn/sigal), which is static site gallery generator.  While definitely not as feature-rich, it gets me closer to what I was after.  While I do let it duplicate my photos, I have my original photo dir mounted in a LXC with Sigal and the ~500G worth of photos are downsized and copied consuming an additional ~3G of space, but it works well.  

Just another option.

**Comment by ReSearchITEng** [comment]
@electerious any plans to have an option like Sigal does?
Anyone aware of any other software in the meanwhile?

**Comment by valessiobrito** [comment]
I would like to keep the original structure of my "Photos" folder and not have duplicate files on my machine.
The workaround for importing would be to register remote or local directories, for example:
You could register locally:
/home/user/Images/photos
/home/user/Images/especial-photos

And remotely, you could also register Dropbox or OwnCloud Directories (WebDav) (this is case, replicate/download the fotos in local/server).

**Comment by heiko73** [comment]
Hi, I just came across lychee on my search for a nice webserver-based photo gallery for my family server and this stopped me right away. I also checked out sigal and it is a pain to install (unlike lychee, which was up and running in a minute), to no avail.

Using file access permissions to keep lychee from deleting the originals is no solution, as I a) would be afraid that I somehow set the permissions in a wrong way and my orginals in their archive folder structure are lost and b) I would duplicate my 70k+ photos on my server, wasting diskspace big time.

My proposal for a solution:
1. use symlinks to not touch the original files (for all the good reasons already mentioned here)
2. never touch the originals, if someone wants to rotate, resize or change the pictures in whatever way, copy the original and work on the copy

This way, you keep all your original files untouched, do not need write access to them and at the same time reduce duplicates to a bare minimum (only consume additional storage space for those photos that are edited in some way).

I use Lightroom to manage my photos, but I would love to have an easy way to allow my family members to browse through all the pictures using their phones, tablets, laptops etc. 

I will give lychee another try when this has been fixed. In its current state, the philosophy behind handling the files is unfortunately incompatible with my personal way of storing and managing my photos.

**Comment by michael-reed-hampton** [comment]
Would really like it if this was non destructive as well.  I agree with comments here that leaving files in place would be better, or at the least having an option to NOT delete the source.  As is, I am copying files to a separate location just so lychee can import them and I do not have to worry about these files being deleted.

**Comment by 3phreal** [comment]
I'm also a new user who found this app on the web. It has all i want from such an app. Except the Deleting files part. Any news on a change to this feature ?

**Comment by 29z** [comment]
This looked really good, until I seen someone post about how it deletes your photos.. yikes. Thanks anyways.

**Comment by snazzybunny** [comment]
same here :O. Deleting the source is not worth it for me.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
