### ISSUE TITLE
Individual photo view problems

### ISSUE THREAD

**Issue by oxpa** [electerious/Lychee#640]
Hello,

I'm using lychee from 'subalbums' branch, which is a little ahead of master.
When I open individual photo CPU usage goes really high. I've noticed, that there is something wrong with automatic zooming as it causes CPU usage all the time.

A suppose, it would be nice to reimplement zooming: disable automatic one and enable 'fullscreen zoom by double click', which should allow switching images back and forth with clicking on the side of a screen or tapping space button, but should keep UI static.

I saw a good implementation for a lazy load image gallery at https://github.com/metafizzy/flickity . I belive, you could adopt some code from it.

If you'd like, I could integrate flickity into lychee. This would resolve several UI problems at once (while I'm still not sure on how to organize overlays with additional photo data, cause I can propose several good approaches)

Please, share your vision of a possible solution and further development direction.
Thanks in advance.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
