### ISSUE TITLE
Support for *.webm & *.gifv format

### ISSUE THREAD

**Issue by gsantner** [electerious/Lychee#645]
### Detailed description of the problem
Currently the `.webm` &  `.gifv` extensions are not supported.
Some sites tend to rather publish `webm`'s or `gifv`'s instead of `gif`'s (for the good, ..e.g. filesize), 
it would be great if these formats could be also supported in lychee.

### Steps to reproduce the issue
* Try to upload `*.webm` /  `*.gifv` file
* See that it is not supported :D

Related to Issue No. 63 I think..

**Comment by UdoKifferbrehl** [comment]
Does anyone know a gallery like Lychee which supports those two formats? I do not think that they will be added to Lychee because it is a photo management tool (not video management).

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
