### ISSUE TITLE
Diagnostics fails to open

### ISSUE THREAD

**Issue by wrek** [electerious/Lychee#648]
In chrome, Lychee 3.1.4, clicking on Diagnostics returns the following error:
Fatal error: Can't use function return value in write context in /home1/[snip]/public_html/Lychee/plugins/Diagnostics/index.php on line 97

**Comment by electerious** [comment]
It's probably a problem of your PHP installation. Please take a look at your PHP error log for more details.

**Comment by JackFarrand** [comment]
Line 97 of index.php is as follows:

`if (empty(ini_get('allow_url_fopen'))) echo('Warning: You may experience problems with the Dropbox- and URL-Import. Edit your php.ini and set allow_url_fopen to 1.' . PHP_EOL);`

for some reason PHP 5.3 - 7.0 (both tested) dies when checking the php.ini for this value, just comment out line 97 and it will work just fine.

@electerious A1 skills there man, I recommend using the torvalds school of thought, it's up to you not to break userspace!  Or in other words, if it can be fixed in your code it should be.

**Comment by wrek** [comment]
Which index.php?

**Comment by JackFarrand** [comment]
@wrek /home1/[snip]/public_html/Lychee/plugins/Diagnostics/index.php

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
