### ISSUE TITLE
multi-select without click and drag

### ISSUE THREAD

**Issue by williamkray** [electerious/Lychee#649]
This is a feature request for some method of selecting multiple photos or albums without needing to click and drag to select them (which you typically can't do from a touch interface). perhaps some sort of checkmark overlay button, similar to what google photos does? i'm not sure how complex this would be to implement, but it seems like it would all happen on the javascript side. 

this change may also mean that the right-click option to take action on the selected pictures would need to move to a floating "Actions" button that appears when things are selected (although this may not be necessary depending on implementation).

**Comment by daveballan** [comment]
Ya, plus one on this! Maybe a shift-click to select more than one. This will allow far easier tagging etc.

**Comment by ekianjo** [comment]
Definitely interested by this one as well!

**Comment by raphaelkottakal** [comment]
Yes pls

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
