### ISSUE TITLE
Request: Duplicate+Move

### ISSUE THREAD

**Issue by RiotTee** [electerious/Lychee#650]
### Detailed description of the problem

There is a button to duplicate a photo. If you do it on several photos then you have to move each to another album. It would be nice to have a **Copy to...** button to duplicate and move at once.

**Comment by electerious** [comment]
Good idea. That would be a helpful feature.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
