### ISSUE TITLE
Is there still any way to manually sort albums and photos?

### ISSUE THREAD

**Issue by teohkay** [electerious/Lychee#651]
I understand that this has been a pretty hard thing to do based on my research on previous requests for this feature.

How is it looking atm? If the devs aren't working on a feature to sort albums manually, is there a way around this? Maybe by editing the database values?

I host a medium sized gallery and most of my photos are sent to me by people and I cannot rely on each and every one of the photos having metadata that is accurate. This results in a very messy gallery and I would like to be able to sort albums manually.

**Comment by electerious** [comment]
The [album and photo sorting](https://github.com/electerious/Lychee/blob/master/docs/Settings.md#album-sorting) in the database settings table accepts any kind of MySQL query. I'm sure that there's a workaround, but not a convenient one. You could edit/add the dates manually (`takestamp`) or create a new field for a custom sorting.

**Comment by teohkay** [comment]
Thank you for the suggestion. I find it frustrating that I didn't think about manually sorting albums via a new field... I just did that and it works perfectly. Not super convenient but it works and it's not a huge pain in the ass :)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
