### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by cts-prog3** [electerious/Lychee#654]
Is there documentation on how to use Lychee?  I would like to know things like what type of resizing is done when a photo is uploaded, what features are available when Imagick is enabled, what exif fields are brought in.  My GPS properties do not seem to be there.

**Comment by cts-prog3** [comment]
One specific question I have is how is the PHP Zip extension used?

**Comment by electerious** [comment]
There's currently no detailed documentation that answers your question.

The PHP Zip extension is used for album downloads (It's possible to download an album as a zip archive).

**Comment by electerious** [comment]
- Imagick allows faster processing and creates a medium-sized version of each uploaded photo. The smaller photo will be displayed on smaller screens.
- Lychee won't import GPS properties
- You can find all supported metadata in [the source](https://github.com/electerious/Lychee/blob/master/php/Modules/Photo.php#L764)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
