### ISSUE TITLE
Incorrect integer value: '' for column 'takestamp' at row 1 when adding photo

### ISSUE THREAD

**Issue by cts-prog3** [electerious/Lychee#656]
When I ad certain photos I get this error message.  I installed Lychee for the first time about a week ago.  Here is a screen shot of what the properties look like.  Any ideas?

![lychee picture properties](https://cloud.githubusercontent.com/assets/7528702/20741531/967f1ef2-b716-11e6-9542-61f06aa8b83a.PNG)

**Comment by qligier** [comment]
Maybe related to #585. Could you extract the exif data of the date taken for images that you can't upload please? You can do it online, by example with exifdata.com

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
