### ISSUE TITLE
Lychee not staying logged in, random logouts on desktop and immediate logouts on mobile

### ISSUE THREAD

**Issue by ghost** [electerious/Lychee#660]
Not sure if this is a problem with my setup (Apache2, PHP5, MySQL, Ubuntu 14.04 LTS, etc. - standard setup), intentional, or a bug, but I can't seem to figure it out. Basically, Lychee doesn't seem to like staying logged in, even with cookies allowed. On desktop Chrome and Firefox, it seems to log itself out completely randomly, regardless of if the tab is active or not. On mobile Safari in iOS, it'll log itself out immediately if the tab has to be refreshed or reloaded. 

Is this behavior intentional? My Lychee diagnostics don't report any error codes and everything else seems to work fine. If it isn't intentional, any ideas what might be wrong?

**Comment by electerious** [comment]
It's not a problem I'm aware of. Could be the PHP session timeout. Maybe this helps: https://github.com/electerious/Lychee/issues/402

**Comment by AileSc** [comment]
Unfortunately, that did not help. I even set a max cookie/login time to 24 hours instead of 0 (aka: logout when browser closed) and still have random logouts on iOS.

**Comment by electerious** [comment]
[](url)This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
