### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by EliasDeVos** [electerious/Lychee#663]
### Detailed description of the problem
Hi i have some questions about the tagging, can you have an overview of all the tags ? and can you add an existing tag to a photo ? and can you search on these tags in all your photos ?
couldn't find it in the live demo

**Comment by ThiloL** [comment]
I also would liek to see a list of all tags und the possibility to add something to the list of available tags.

**Comment by daveballan** [comment]
Plus 1 on this request!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
