### ISSUE TITLE
Share Album menu vanishes on click

### ISSUE THREAD

**Issue by josch** [electerious/Lychee#666]
Hi,

I can reproduce this issue on your demo system with firefox and chromium.

After sharing a directory, I want to copy the link to it. On GNU/Linux systems copypaste can be done via the selection buffer. All text that gets selected with the mouse curser ends up in that buffer and can later conveniently be pasted by a click of the middle mouse button.

Unfortunately, doing so seems to be impossible with the Lychee web interface. This is because after a click on the Share Album icon, I see the share url but I'm unable to copy it because any click with the mouse button will let the menu vanish immediately.

I suggest that clicking on the textbox should not let the menu vanish.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
