### ISSUE TITLE
Upload photo failed, and get "Server returned an unknown response."

### ISSUE THREAD

**Issue by tzuxung** [electerious/Lychee#669]
### Detailed description of the problem
Upload photo from PC but failed, it said "server returned an unknown response. please take a look at the console of your browser for further details", /data and /uploads is writeable.
### Browser and system
Chrome Win10

**Comment by electerious** [comment]
More information necessary to reproduce the issue (e.g. diagnostics, the photo, etc.)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
