### ISSUE TITLE
include api and bulk import from url

### ISSUE THREAD

**Issue by Fshamri** [electerious/Lychee#670]
This is awesome application but it lacks API to communicate with 3rd party apps like mobile apps. Do u have plan to include api?

secondly, how is it possible to upload or import images from bulk urls?

Thanks a lot

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
