### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ThiloL** [electerious/Lychee#673]
I would like... 

1. a direct link to a picture **without** public sharing.
If i click on the eye, I get a direct Link, but the picture is public then.

2. a shorter, smarter an nicer direct Link... insteaf of ".../view.php?p=123445667" - "/view/123445667" would be nicer. URL-rewriting.

Kind regards, Thilo

**Comment by fly-man-** [comment]
@ThiloL Feel free to submit a PR if you have ideas about this

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
