### ISSUE TITLE
Serving large albums with limited PHP memory fails

### ISSUE THREAD

**Issue by rainman110** [electerious/Lychee#674]
### Detailed description of the problem
On shared hosters, serving large albums is practically impossible to due lack of memory.
Lychee uses PHP's readfile function to transfer the data.

For shared hosters, it would be good to directly download the zip file without using PHP in between. The zip file name could be encrypted or hashed, to be not guessable. 

### Steps to reproduce the issue
Install lychee on a shared hoster such as Alfahosting, Strato ... Then try to download a very large album (about 1 Gb) .

### Output of the diagnostics (Settings => Diagnostics)
I got no particular errors in the logs. The download just stops at about 540 Mb.

### Browser and system
Chrome / Mac OS 10.11

**Comment by qligier** [comment]
As [described in the doc](http://php.net/manual/en/function.readfile.php), PHP's readfile does not store the file in memory but writes it directly in the output buffer.

Your issue should be the Zip compression, ZipArchive does store the whole zip in memory. It should not be able to create an archive of about 1Gb on a shared hoster. It has been discussed in #538 (with no solution for now).

**Comment by rainman110** [comment]
@qligier I modified the code on my personal fork, that it caches the zip file. This allows me, to pack it locally and upload it via ftp.

Then I get the issue while sharing the already packed zip to the client.

**Comment by qligier** [comment]
So you have a valid Zip file on the server, you serve it with PHP's readfile and the download is still corrupt? I see two other possibilities:
[PHP's output buffering](http://php.net/manual/en/zlib.configuration.php#ini.zlib.output-compression) could be activated or Apache (mod_deflate, mod_gzip)/nginx (ngx_http_gzip_module) could be buffering the response to compress it. Have you checked Apache/nginx logs?

A solution could be to use the X-Sendfile/X-Accel-Redirect headers to force Apache/nginx to serve the file instead of PHP but it requires a special configuration of the server. It also breaks the current implementation, as you can't delete the file after use anymore.

**Comment by qligier** [comment]
PHP timeout is also possible but that should be visible in the logs.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
