### ISSUE TITLE
How to change temp download folder directory ?

### ISSUE THREAD

**Issue by LuffyyyffuL** [electerious/Lychee#677]
Hello,

I would like to change temporary download folder directory for accelerate the zip building.

It's possible ?

Thank you :)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
