### ISSUE TITLE
[Enhancement] Album by tags?

### ISSUE THREAD

**Issue by albansch** [electerious/Lychee#683]
Hi,
Did I miss something or it is not possible to see album by tags?
Thanks.

### Detailed description of the problem
It appears to me that it is not possible to see albums by tags.

### Steps to reproduce the issue
When adding tags to pictures, if tags are common between multiple pictures, I would like to see the tag as an album.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
