### ISSUE TITLE
Add graphicsmagick image processor support

### ISSUE THREAD

**Issue by LexiconCode** [electerious/Lychee#685]
Currently Lychee supports Imagick aka ImageMagick. depending on the hardware and resource graphicsmagick can be quite a bit faster.

For reference
https://coderwall.com/p/1l7h-a/imagemagick-bloat-graphicsmagick

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
