### ISSUE TITLE
How to add og:image tag to page?

### ISSUE THREAD

**Issue by vlos** [electerious/Lychee#691]
### Detailed description of the problem
I setup lychee photo gallery and want to post to REDDIT the images, where REDDIT will set the link icon to the image.  I believe I need to add og:image meta tag, but have no clue where to add it..

**Comment by electerious** [comment]
Lychee adds those tags automatically when you use the share-link of a photo. Click the eye-icon on the top right and copy the text of the input.

**Comment by vlos** [comment]
Ok, I had tried just posting the simple gallery link, but that works.

Thanks

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
