### ISSUE TITLE
Captured time in info sidebar for photo

### ISSUE THREAD

**Issue by Rurik19** [electerious/Lychee#692]
In the photo info sidebar it would be great to have create time too.

**Comment by Rurik19** [comment]
like this :-)
![image](https://cloud.githubusercontent.com/assets/1955806/24796248/ab6f1166-1ba5-11e7-8ac6-366be2ac1ca1.png)
I'll make PR today

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
