### ISSUE TITLE
Share Image/Picture across multiple albums?

### ISSUE THREAD

**Issue by vlos** [electerious/Lychee#694]
### Share Pictures across multiple albums without adding image more than once?
My images could easily fit into different categories (based on tags), is there a way to share the images across multiple Albums without having to add it twice.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
