### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERRORBY when I try to download

### ISSUE THREAD

**Issue by joshuaavalon** [electerious/Lychee#697]
### Detailed description of the problem
Chrome show ERR_SPDY_PROTOCOL_ERRORBY.
Firefox show error after show the dialog box.
I can download with download manager but not with broswer

### Steps to reproduce the issue
Download a photo or album from browser.

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50717
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.2.1
Plugins:         
### Browser and system
Chrome  57.0.2987.133
Firefox 52.0.2

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
