### ISSUE TITLE
disable share icon when public

### ISSUE THREAD

**Issue by augras** [electerious/Lychee#701]
Hi,
Thanks for Lychee I just begin to use.
When an album or a photo is public there is automatically the share icon. How can i disable this icon ? I found anything in the option to make an album or a photo public.
Thanks,
Philippe

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
