### ISSUE TITLE
Need help from developer: photo.getDirectLink() is null in contextMenu.photo

### ISSUE THREAD

**Issue by delmartechdude** [electerious/Lychee#704]
I'm trying to call `photo.getDirectLink()` in `contextMenu.photo` so that I can have an easy right click contextMenu item that has the full, shareable URL that I can put into the clipboard, or into a JS prompt that is automatically highlighted so that all the user has to do is CTRL-C and enter.

My problem is that `photo.getDirectLink()` appears to be null when I call it. Why would that be? Am I doing something wrong? an example of what I was trying to do is also in a closed pull request. (Realized it is probably better to ask here) - #703 

Thanks!

**Comment by delmartechdude** [comment]
@electerious Any ideas on this?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
