### ISSUE TITLE
Import from server auto selects a sub folder based on album

### ISSUE THREAD

**Issue by Zelaf** [electerious/Lychee#706]
### Detailed description of the problem
When you click on "Import from server" the text box is already entered with the folder `uploads/import/`.
Having a second folder entered for example `uploads/import/Animals` when the button is clicked inside an album named Animals, same could happen when you are in an album called Flowers and the auto entered directory becomes `uploads/import/Flowers` etc.

This could help users who use FTP to upload their images to Lychee by making fewer edits and clicks when importing new photos using the Import from server function.

### Steps to reproduce the issue
Click on the Import from server button after clicking the plus.
### Output of the diagnostics (Settings => Diagnostics)
`N/A`
### Browser and system
Firefox 53.0.3 on Windows 10

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
