### ISSUE TITLE
Add support images 360°

### ISSUE THREAD

**Issue by valessiobrito** [electerious/Lychee#707]
Exemple: https://aframe.io/examples/showcase/sky/

Using aframevr.js

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
