### ISSUE TITLE
Feature Request: Vector Support

### ISSUE THREAD

**Issue by dshastry** [electerious/Lychee#708]
Just started using Lychee to manage stock photography. It would be great if there was support for EPS and other vector standard files to be added to the library. Would help massively for us designers who use the system to manage our asset collections!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
