### ISSUE TITLE
Image skipped / unintended double swipe on Android device

### ISSUE THREAD

**Issue by kabieror** [electerious/Lychee#709]
### Detailed description of the problem
When I swipe to the next photo on an Android device and start to swipe outside of the image on the black area, an image is skipped and the second to next is loaded.

![ezgif-3-2add4d5237](https://user-images.githubusercontent.com/16592633/26840039-29cb41c4-4ae5-11e7-848d-bf5b9fd62f5f.gif)

### Steps to reproduce the issue
Use the Chrome debugger (F12) and enable the mobile emulator (Ctrl + Stift + M). Choose the Nexus 5X or Nexus 6P as device and open a Lychee gallery, e.g. https://ld.electerious.com/#5/13902216891974 (You have to reload the page after switching into mobile view in order to enable the swiping feature). Now click or touch the black area in the right of the displayed image and swipe to the left. For a fraction of a second the next picture gets visible, but then another picture change is performed.

### Browser and system
Tested on Lychee 3.1.6 and the public demo site (version 3.1.0).

Verified on the following platforms:
- Chrome 58.0.3029.83 on OnePlus 3 running Android 7.1.1
- Android Emulator inside the Debug Mode of Chrome 58.0.3029.110 (64-bit) for Windows
  - Nexus 5X
  - Nexus 6P

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
