### ISSUE TITLE
How to hide the Smart Albums

### ISSUE THREAD

**Issue by rogboyce** [electerious/Lychee#712]
Hi, 
I just thought I'd share this discovery with other Lychee users. I worked out that I could hide the smart albums by just adding this to the head section of index.html:

<style>
[data-id="0"]  {
    display:none;
}
[data-id="s"]  {
    display:none;
}
[data-id="f"]  {
    display:none;
}
[data-id="r"]  {
    display:none;
}
</style>

Hope it helps someone out there.

**Comment by peterberbec** [comment]
Great! Thanks

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
