### ISSUE TITLE
Is there a way to only show smaller photos?

### ISSUE THREAD

**Issue by LaszloHont** [electerious/Lychee#715]
### Detailed description of the problem
My original size photos (the photos the visitors can download if they want) are really really big. Is there a way to show smaller filesize versions instead? I enabled the medium plugin but that doesn't seem to help. The visitors might have good screens but their bandwidth is not good :(
Ideally setting a lower quality (say 95) would be great.

### Browser and system

**Comment by buczo23** [comment]
+1, same here. It could be a nice feature to get extra setting for that, show Size = 'medium'. As for now it is based on screen resolution. @LaszloHont rescaling of the pictures are made on server side, problem is related to the screen resolution which "dictate" which version of picture to load (small/medium/big), novadays it will be big most of the time.

**Comment by LaszloHont** [comment]
Also a config option for quality, useful for when the shots are 100% jpegs (like straight from a photographer who has converted from raw).

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
