### ISSUE TITLE
Lychee MYSQL backup

### ISSUE THREAD

**Issue by dm807cam** [electerious/Lychee#722]
Could you please clarify the mysql backup and restore process a little more in detail in the README?
That would be tremendously helpful!

**Comment by saulius-s** [comment]
This is a part of my backup script: 

Database export:
mysqldump --routines -h localhost lychee > /home/server/Backup/lychee.sql -u root -p 

Database import:
mysql -u root -p lychee < lychee.sql

Would be nice to see others backup solutions.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
