### ISSUE TITLE
Couple of feature requests

### ISSUE THREAD

**Issue by evitalis** [electerious/Lychee#727]
There may be already issues for these open but I have not seen recent activity on them. I am also wondering if this project is still maintained.

I am wondering if it is possible to remove/hide the smart galleries, and if there is a way to use PostgreSQL? The forced MySQL is holding me back from this project at the moment but it looks like just what I have been searching for.

**Comment by jaywilliams** [comment]
The only current supported database is MySQL. In the future, switching to PDO may be possible, see #83

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
