### ISSUE TITLE
Possible Memory Leak when uploading

### ISSUE THREAD

**Issue by alexanderharm** [electerious/Lychee#729]
### Detailed description of the problem
I upgraded to the latest version 3.1.6 and my server quickly runs out of memory when uploading several images. The memory limits set in the php.ini and php-fpm.conf are exceeded by far until the server crashes (SmartOS, NGINX, PHP 7.0.21). In the browser console an error is reported.
If I downgrade to 3.1.5 the problem does not occur.

### Steps to reproduce the issue
Upload roughly 50 images around 2.5 MB each. 

### Output of the diagnostics (Settings => Diagnostics)
```
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!


System Information

------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          SunOS
PHP Version:     7
MySQL Version:   50505
Imagick:         1
Imagick Active:  1
Imagick Version: 1798
GD Version:      2.2.4
Plugins:    
```

### Browser and system

```
macOS 10.12.6
Firefox latest
```

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
