### ISSUE TITLE
Sharing Hidden does not work in 3.1.6

### ISSUE THREAD

**Issue by alexanderharm** [electerious/Lychee#730]
### Detailed description of the problem
Sharing Hidden does not work. Error in Browser something like `function getAlbumByID not implemented` or so.

### Steps to reproduce the issue
Share an album via the option `Hidden`, copy/paste link in Browser.

### Browser and system

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
