### ISSUE TITLE
Multiple User Support

### ISSUE THREAD

**Issue by Ayokas** [electerious/Lychee#732]
Hi there,

so far I like Lychee but I am wondering: Is it possible to implement mutliple user support? Or does it exist already and I am too blind to find it?

Would be glad to hear about it =)

**Comment by sellers** [comment]
Multi-user may need to be broken into multiple pieces
* allow data store to be modified by multiple computers (authentication via another method, afp mount, computer login, etc)
* allow multiple users to have separate libraries
* built-in authentication to access a shared library 

Then you have the aspects of multiple people accessing simultaneously

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
