### ISSUE TITLE
Minify Javascript Code Myself

### ISSUE THREAD

**Issue by tvdmitrii** [electerious/Lychee#733]
It is not really an issue. I wanted to add some functionality myself.

For example include tags in picture files when you are downloading the album or have ability to download your search results the same way as albums (useful when your friend wants all pictures with him/her).

There are javascript files in lychee/src/scripts/ however they are no used, so changes to them do not have any effect. lychee/dist/main.js is a file that is actually used. It is all files from scripts folder jammed together and minified. I was wondering what software do you use to jam and minify multiple JS files.

**Comment by lopisan** [comment]
It is minified using Gulp (and its plugins). See the [Lychee/docs/Build.md](https://github.com/electerious/Lychee/blob/master/docs/Build.md) for description how to do it. You have to install NodeJS and use npm.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
