### ISSUE TITLE
Can't upload photo using mobile Jelly browser

### ISSUE THREAD

**Issue by lgg42** [electerious/Lychee#735]
# Server System Information 

Lychee Version: 3.1.6 
DB Version: 030102 
System: Linux 
PHP Version: 7.1 
MySQL Version: 50544 
Imagick: - Imagick Active: 1 
Imagick Version: - GD Version: 2.2.4

# Android phone
### Full user agent string is:

Mozilla/5.0 (Linux; Android 7.1.2; Moto G4 Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.78 Mobile Safari/537.36

-------
I tried Chrome browser and it worked flawlessly. Nevertheless, when I use my OS' included browser, Jelly, it fails to upload the picture. I get the dialog for selecting the fine but that's it. After that the file does not get uploaded.

### Full agent string using Chrome Browser:

Mozilla/5.0 (Linux; Android 7.1.2; Moto G4 Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.107 Mobile Safari/537.36

### For both Jelly and Chrome

Javascript enabled: Yes

Cookies enabled: Yes 

_Sent from my Motorola Moto G4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
