### ISSUE TITLE
FEATURE: Shopping Cart System

### ISSUE THREAD

**Issue by mitchellkrogza** [electerious/Lychee#736]
Just got pointed to this repo by a friend on Github, looks stunning and is very fast. 
Any chance you have a shopping cart system / plugin in the workflow for the future?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
