### ISSUE TITLE
[Dropbox] Photo title encoded and truncated at 30 char

### ISSUE THREAD

**Issue by BenoitLavergne** [electerious/Lychee#737]
When I use the Import from Dropbox feature, the photo title is url encoded (" " , "%20").
Furthermore its name is truncated at 30 char.

The issue can be reproduced each time (not present if Import from server).

Diagnostics
-----------
Warning: You may experience problems when uploading a large amount of photos. Take a look in the FAQ for details.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     5.6
MySQL Version:   50557
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      2.1.1-dev
Plugins:         

### Browser and system
Client :
Chromium 59.0.3071.109 FR
Xubuntu 16.10
Server :
Debian 8 apache 2.4.10 php5.6.30

**Comment by fly-man-** [comment]
#558 is the pull request that will fix this. It will allow up to 100 characters then

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
