### ISSUE TITLE
Photos in public album not visible 

### ISSUE THREAD

**Issue by apsarapea** [electerious/Lychee#739]
Hi, I really love Lychee, looks great and it's lightning fast. Only thing is that after uploading images to the public album, once logged out, it is not visible at all. Any ideas?

**Comment by rokx** [comment]
You must make it public. Go into the album and click the eye in the top right corner. Approve by clicking "Share album".

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
