### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by albertobatist** [electerious/Lychee#740]
Hello, 
I would like to congratulate the project and would also like to know if it has a forecast for a new version? Is it possible to create subdirectories?

Thanks!

**Comment by FionaHagen** [comment]
Yes, it is possible to create subdirectories.
A new version will be available when it is done, I think that will be the case next year. 
You are welcome to check out the [live demo](https://ld.electerious.com/).

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
