### ISSUE TITLE
Cursor misplaced on mobile / tablet

### ISSUE THREAD

**Issue by dylanoyer** [electerious/Lychee#744]
### Detailed description of the problem
When trying to login on mobile devices, the cursor starts way below the password line, when trying to login via a user as well as an admin
( can be seen over Matthews album)
### Browser and system
Safari, all iOS devices, iOS 11
![1ba68fdb-12c3-4d82-80db-ba417283e2d7](https://user-images.githubusercontent.com/15711347/31319346-a45405b0-ac2f-11e7-8c42-3653ecdce4c0.png)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
