### ISSUE TITLE
Sharing of pictures in hidden and password protected galleries = photo not found

### ISSUE THREAD

**Issue by waszumKUCKUCK** [electerious/Lychee#745]
### Detailed description of the problem
Once I share a picture out of a hidden and password protected gallery in Facebook, the picture appears in Facebook, but if you click on the link, there come a message: Photo not found!

### Steps to reproduce the issue
You can use this test environment to reproduce this issue:
Gallery: http://galerie.sebastian-muthwill.de/#15083928414000
Password: 12345
Shared Pic:  http://galerie.sebastian-muthwill.de/view.php?p=15083932625500

### Output of the diagnostics (Settings => Diagnostics)
Diagnostics
-----------
Warning: Dropbox import not working. No property for dropboxKey.
No critical problems found. Lychee should work without problems!

System Information
------------------
Lychee Version:  3.1.6
DB Version:      030102
System:          Linux
PHP Version:     7
MySQL Version:   50715
Imagick:         1
Imagick Active:  1
Imagick Version: 1673
GD Version:      bundled (2.1.0 compatible)
Plugins:       
### Browser and system
Firefox, Windows 7

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
