### ISSUE TITLE
New feature - Add multiple user accounts

### ISSUE THREAD

**Issue by brezlord** [electerious/Lychee#746]
I would like to suggest the following feature. 

It would be nice to have the ability to have multiple user accounts with the ability to share photos and albums with other accounts. Only the account that uploads the photo can delete them.

Keep up the excellent work.

Kind Regards,
Simon

**Comment by kushimato** [comment]
i provide this idean and i'm also on research of this subject.  This is what i very need function and i will find a way and share the solution if i can.  Good system but need's to be a magic touch and this feature is what i meaned from magic....

**Comment by kushimato** [comment]
First of all we need those basic element's to add : 

- Very clean and simple re-capatcha activated registiration form ( also with social logins provided )
- Sub directory creating for each users under UPLOAD folder
- User only permitted administration dashboard system after login ( can only edit his/her uploadings )
- User privacy module which they can choose their uploads private or public or for only followers
- Ajax Member's Search autofill 

After all if we can create those options Lychee will become a great Photo & Image sharing community script.  I really want to do that and just started to work on those features.  I will share all information soon 

-

**Comment by half-shell** [comment]
Hi there. I am a recent but honestly amazed user of Lychee, and how simple and easy it is to use and setup. I chose Lychee as my remote hosting photo platform because it is independent of any other services out there, and doesn't try to be what it is not: an online photo storing social platform, which there are many of already out there.
It stores photos, and make theme really easily accessible to others, without an account. That's it.
And I strongly believe that any attempt to make it a so-called "social" platform won't do it any favor. At least certainly not in my eyes.

@kushimato If those features you're talking about were put into Lychee when I was looking for a self-hosted photo-platform, I wouldn't have chosen it. Because IMHO, those features you are talking about don't suit Lychee as a simple self-hosted platform.

All that said, I do believe that a simple multi-account setup can be useful to have several people manage a single instance of Lychee. But not in a "check out and follow my profile" kind of way. Rather to make several person put their album online, and make them shareable as easily as the unique admin there is now.

**Comment by cyveros** [comment]
@kushimato @brezlord I came across this project a while ago and spent some time to understand its source code. Here is my remarks:


- Lychee does not foresee any multi-account design. There is only one user which is the admin.
- Lychee's internal Admin/Guest pattern of workflow limits its potential to support additional accounts

For security:
- Lychee is not production ready. It has many serious SQL injection attack vulnerabilities.
- In theory, given poorly configured web server. db credentials (within `/config` ) can be publicly accessed (WTF?)
- most of php source file can be directly invoked

there're also bunch of problem for the frontend scripts

My conclusion is: it is very hard to evolve under current architecture.

I'm currently working on rewrite the lychee's backend code and port current backend to a silex based microservice architecture.

https://github.com/cyphp/litchi/tree/4.0.0/

if you're familiar with php development, you may give a look =)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
