### ISSUE TITLE
Can't install on web server , but work on local server

### ISSUE THREAD

**Issue by shyan00772** [electerious/Lychee#749]
### Installed on local server but api server problem but when install on web server showing -

 //Forbidden

You don't have permission to access /albums/Lychee/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.//

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
