### ISSUE TITLE
[Feature Request] Make Own Database

### ISSUE THREAD

**Issue by mccorkled** [electerious/Lychee#750]
It would be great if Lychee could make its own database. I have been trying to set this up for a while now and you have to have mariadb, then use mysql workbench or administrate it via cli to access it. It's all just very confusing. 

There is another version of Lychee that makes its own db but it hasn't been updated in over a year. 

Thanks.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
