### ISSUE TITLE
npm dependencies out of date

### ISSUE THREAD

**Issue by arnonm-intel** [electerious/Lychee#751]
### Browser and system

**Comment by arnonm** [comment]
patch attached to fix dependencies. 
[babel.zip](https://github.com/electerious/Lychee/files/1431395/babel.zip)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
