### ISSUE TITLE
Import script --Missing Functions.php

### ISSUE THREAD

**Issue by kapone** [electerious/Lychee#752]
Hello!  

I am currently attempting to install and run the import script as seen here:
https://gist.github.com/electerious/2a74579fbc2bd32971b5

I have placed the following file in the Lychee/php directory and am attempting to run it from the command line using php -f import.php. After running this the first time I was receiving errors regarding the missing config.php file so I copied it in. I am still receiving the below error for the missing functions.php file. I ran find from the command prompt and could not find this file anywhere.

Any help would be appreciated. Thank you!

PHP Warning: require(functions.php): failed to open stream: No such file or directory in /var/www/html/Lychee/php/import.php on line 8
PHP Fatal error: require(): Failed opening required 'functions.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/Lychee/php/import.php on line 8

I am running PHp 7 with NGINX on raspbian.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
