### ISSUE TITLE
Reference simlink when importing from local machine

### ISSUE THREAD

**Issue by mildfuzz** [electerious/Lychee#753]
I do not wish my images to be imported into Lychee, as this will dominate too much space duplicating the files. Can it be configured to use simlinks?

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
