### ISSUE TITLE
Is there a way to search photo by date range ?

### ISSUE THREAD

**Issue by GMaxera** [electerious/Lychee#755]
I'd like to be able for retrieve all photo uploaded/created into a specified date range.

Is this supported ? and if not, it's possible to create a plugin for add this functionality ?

Thanks.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
