### ISSUE TITLE
[help/not-a-bug] How to add own HTML code and page?

### ISSUE THREAD

**Issue by HydraGene** [electerious/Lychee#757]
This is not a bug, but since there isn't any community to be found other than Github, I'll ask for help here.

I would like to add my own code. The website now, shows nothing more than the gallery itself. But I would like to add a welcoming message etc.

I have tried editing the index.html, but it doesn't seem to work. Or the text ends up behind the gallery so it can't be seen.
Where would I add the code so that it would be visible, for example, between the "Smart Albums" and "Albums" of my website?

Secondly, how would I add a page? Like adding a home page with a message.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
