### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Unresponsive** [electerious/Lychee#763]
electerious haven't been seen for a long while and he is the main (only?) contributor.

Woud you consider this project dead by now?

**Comment by illyaking** [comment]
That is sad. I really like Lychee.
I'm new to Github. What happens to abandon projects?

**Comment by tobru** [comment]
I don't think that it's dead: https://twitter.com/getlychee/status/934004329849159680

**Comment by Unresponsive** [comment]
I hope it's true but actions speak louder than words…

**Comment by illyaking** [comment]
Oh, awesome! I am glad.

**Comment by petrk94** [comment]
Im wondering what the reason is?
Just time? Does it would help maybe a donating campaign?

**Comment by mastacheata** [comment]
> What happens to abandon projects?
Nothing?!

**Comment by hitam4450** [comment]
I think this was it ! Another Open Source failure !

**Comment by guzzisti** [comment]
I'd rather say: Another Community Failure.
You're all free to fork the code and keep making it better.

**Comment by petrk94** [comment]
> I'd rather say: Another Community Failure.
You're all free to fork the code and keep making it better.
@guzzisti I think thats the wrong way, it were better to work together, instead of forking just a project.
But the core problem what I have noticed even in other projects is, that there is always a lack of PHP developer, I cant PHP, just HTML and CSS, so in design fixing I could help, but not in PHP coding. So I think this is the problem.

**Comment by haivala** [comment]
What we need is "official" developer to take care pull requests

**Comment by LudovicRousseau** [comment]
The project was active from 2014 to 2016 https://github.com/electerious/Lychee/graphs/contributors
It looks like @electerious lost interest in Lychee and moved to some other projects. You can see he is still active on his other projects https://github.com/electerious

It is not surprising for a Free Software developer to move to something else. What is needed now is to get other developers to continue the great work on Lychee, or move to another, maintained, gallery software (maybe http://www.photoshow-gallery.com/)

Anybody wants to organise the future of Lychee?

**Comment by petrk94** [comment]
For your information, I have told the php reddit community about it in the hope we get some help from them. So as I see the system, is not very developer friendly, but there is a interest.

https://www.reddit.com/r/PHP/comments/7yi2fc/help_for_a_great_github_project_a_great_looking/

**Comment by mastacheata** [comment]
Lychee isn't of horrible quality, but you can see that it was built by one person and made mostly for their own use.
It mostly suffers from the not-invented-here syndrome (when you write everything yourself, just so you don't have to depend on others, even if they might have had more experience or did a better job - Especially the database handling jumps right at you for this point)

**Comment by LudovicRousseau** [comment]
I see that @fly-man- is actively working on Lychee. See https://github.com/electerious/Lychee/pull/771
Should we all switch to https://github.com/MicroWorldwide/Lychee and continue the development there? I have no problem with that.

**Comment by tobru** [comment]
Best would be to create a Github [organization](https://github.com/organizations/new) and move the code over there. This way the code wouldn't belong to a single person but to a community and it makes it much easier to add new contributors.

**Comment by fly-man-** [comment]
@LudovicRousseau @tobru I have no issues making a new Organization if @electerious no longer works on Lychee.

I send him an tweet earlier today about #771 which I haven't seen a response on yet.

**Comment by tobru** [comment]
I seems that @electerious doesn't have time to work on this project currently, see https://twitter.com/getlychee/status/934004329849159680. We should ask him if he would be willing to handover the project to the community. @electerious: What do you think?

**Comment by LudovicRousseau** [comment]
I was also thinking about creating a github organisation. We can't use https://github.com/Lychee as this name is already used. Maybe Lyche-org or something similar.

**Comment by fly-man-** [comment]
@LudovicRousseau There is always the possibility to request Github Support to ask the **"Lychee"** user if he has issues with changing his username in favor of the Organisation.

**Comment by LudovicRousseau** [comment]
That would be perfect. It looks like @lychee user is not active _at all_.

**Comment by fly-man-** [comment]
Update: I just gotten a message from @electerious that he will respond in this issue with his future plans for Lychee.

https://twitter.com/electerious/status/967492414742155264

**Comment by electerious** [comment]
Sorry for being quiet for so long. It's time to answer your questions!

First of all: It's amazing how healthy the community of Lychee is. Big thanks to everyone who helps us to bring the project forward 🙏

I stopped working on Lychee for multiple reasons:

1. The project got a lot of attention and I started to get a lot of emails. I tried to answer all of them for a while, but I realized that I can't code when I spend all of my free time commenting issues on GitHub.
2. Maintaining a project at this size requires a lot of time and I don't want to spend all my free time on Lychee. That's why I moved on to smaller projects/frameworks. Those're easier to maintain beside a full-time job.
3. The source of Lychee isn't of horrible quality, but it's hard to maintain. I've written it a few years ago for a university project. I learnt a lot and won't write it like this, again.
4. This is properly the biggest reason: I'm only using Lychee rarely for myself.

Let's imagine I would write Lychee from scratch. Here's what I would do:

- UI: I still like the UI, so I won't change the look of it.
- Front-End: The front-end is written in vanilla JS with some jQuery. This makes it hard to maintain. A new Lychee should be written in React (or in a similar component-based framework).
- Back-End: I personally don't like PHP. I would only stay with it so I don't entirely forget how to use it. My choice would be to use [next.js](https://github.com/zeit/next.js/) (A Node.js based framework). This would bring the front-end and back-end closely together and everything would be written in the same language.
- MySQL: Setup, connection handling and connection issues are responsible for many GitHub issues. I'm sure that something simpler is enough for most users.
- Tests: Yes, please! I stopped merging PRs because I'm unable to test the whole project everytime someone makes changes to it.

Will I ever do a full rewrite? I don't know. Maybe someday. I'm sure it would be cool to work full-time on Lychee and I'm sure this could be possible with support from the community, but I'm not sure if I would do it.

Feedback to popular Lychee issues:

#132 Just adding support for multiple users isn't enough. A multiuser system only makes sense when you can share albums and photos between users. It would require a lot of changes to make this possible with the current codebase and it's a feature that could introduce a lot of bugs making the project even harder to maintain. I'm not a fan of it.
#223 Often requested, but I'm not a S3 user and therefore not willed to implement it.
#254 There's already a PR adding sub-albums. It was almost done, but I'm stopped working on Lychee before it has been finished. Requires testing and a better "Add Album" Dialog as far as I remember.
#207 A translation would be cool, but again: A lot of work and code changes.

What's next:

I will hand the project over to the community. It's the first time I'm doing this so I'm unsure what will happen :D @fly-man- will be the first collaborator as I saw him putting a lot of work into the project recently.

I will keep an eye on Lychee to see how this works out!

**Comment by tobru** [comment]
Thanks a lot @electerious for this writeup. I can really follow your points, I know it from other projects I worked on. Let's see what happens to Lychee.

**Comment by daveballan** [comment]
Great response @electerious . I've only contributed small code updates to Lightzone many years ago because it didn't work properly with my D610. Perhaps this might become something I get my teeth into? Releasing this to the community is a great example of Free Software at it's best...

:-)

**Comment by fly-man-** [comment]
@electerious Thank you for the confidence and the explanation.

Earlier today I got a message back from Github Support that the user Lychee is still an active "user" which makes the move to an organisation a bit harder. I would like to propose that people think what would be a good name for the organisation in the new issue I have just created.

I think a period of a month to see a good name would be reasonable and then we can make the Organisation in which people can commit to Lychee.

**Comment by petrk94** [comment]
Great that Lychee is not longer a dead open source community project :)

**Comment by petter-** [comment]
It was a long time since I did any serious coding but I do love Lychee and would love to offer translation and testing since I've done that a lot through the years.

**Comment by petrk94** [comment]
@smartlaw-jenkins 
Nice idea, BUT I want to keep Lychee even running on a shared host with restricted permissions.
Already getting Meteor.js or composer etc. on this very hard in some cases.

> Built in (if desired) or external MongoDB (I'm a MySql guy, but hear/see great things about MongoDB
MongoDB can be nice, but its horrible sh*t, because getting it run on VPS or share host you can forget.
It should be even get more audience by normal people who are not deep in tech, so it should be not hard to setup.
For me MySQL or better MariaDB is a better way and if someone want MongoDB, than provide this as option while installing it, but not replacing.

**Comment by hitam4450** [comment]
I think **Lychee Photo Manger** would be an appropriate name for the new (resp. forked) community project!

**Comment by haivala** [comment]
just make it already :)

**Comment by ginsterbusch** [comment]
Now, not wanting to rain on your parade, but the PHP bit is the only reason I've taken a look at this project. But: Yet another random NodeJS / App JS build? Well .. nope. Thank you very much, but: Nope.

cu, w0lf.

**Comment by haivala** [comment]
Is somebody working on this?

**Comment by LudovicRousseau** [comment]
https://github.com/electerious/Lychee indicates:

> Since the 1st of April 2018 this project has moved to it's own Organisation (https://github.com/LycheeOrg) where people are able to submit their fixes to it.

**Comment by petrk94** [comment]
@LudovicRousseau thanks for information. I even doesnt noticed that it has a own new repository now

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
