### ISSUE TITLE
Support for tiffs

### ISSUE THREAD

**Issue by gypsymauro** [electerious/Lychee#765]
sorry I'm no strong with git, but here is the diff for lychee/php/Modules/Photo.php

16,19c16
< 		IMAGETYPE_PNG,
< 		IMAGETYPE_TIFF_II,
< 		IMAGETYPE_TIFF_MM,		
< 		
---
> 		IMAGETYPE_PNG
26,28c23
< 		'.gif',
< 		'.tif',
< 		'.tiff'		
---

**Comment by fly-man-** [comment]
@gypsymauro As long as ImageMagick and GD both support TIFF files I don't see an issue. 

The only problem with TIFF is that you would have to convert it to another format to display it properly without using external plugins.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
