### ISSUE TITLE
Editing tags always autoselects text

### ISSUE THREAD

**Issue by ultramizer** [electerious/Lychee#775]
Whenever i am trying to edit Tags for a picture or a group of pictures, the popup autoselects the text. 

Now, if you upload 10 pictures to an album and give them the same tags, and after that you want to give some particular pictures more tags separately, you always have to click away the text, because it get's selected automatically. If you don't then you overwrite existing tags. This is really annoying, if you have to add a ton of tags to a ton of pictures, and should be easy to fix/disable. I have searched a ton of javascripts and php files, but couldn't find the function anywhere... It has to be just a tiny little snippet somewhere, but i don't know where to look exactly.

I have found the following input field in "/src/scripts/photo.js" which in itself doesn't seem to have any sort of function to autoselect the text:
`<input class='text' name='tags' type='text' maxlength='800' placeholder='Tags' value='$${ oldTags }'>`

I can't seem to find any other place this could be scripted, but it's somewhere. Can someone help me get rid of that feature? Any tips where to search are much appreciated!

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
