### ISSUE TITLE
Select within search results

### ISSUE THREAD

**Issue by jmichiel** [electerious/Lychee#776]
It would be very handy to be able to select multiple photos in search view so you can easily move/delete a lot of photos that show up in a search

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
