### ISSUE TITLE
"script '/var/www/html/Lychee/php/api.php' not found or unable to stat"

### ISSUE THREAD

**Issue by wonx** [electerious/Lychee#777]
### Detailed description of the problem
When trying to install Lychee in a Debian 8 machine, I am unable to finish the configuration. 

I am using apache2 with php5 and mySQL (the versions on the repository). I enter the Lychee subdirectory on my browser and it asks me for the database host, user and password. I enter them, but when I click on "Connect", nothing happens. 

When checking apache logs, i can find the line 
[Mon Apr 02 18:22:47.463561 2018] [:error] [pid 9680] [client 192.168.1.x:60008] script '/var/www/html/Lychee/php/api.php' not found or unable to stat

The file api.php is non-existent on a fresh installation, and it doesn't exist either in the Lychee github page.

How should I continue?

### Steps to reproduce the issue
Install apache
Install mysql
Install php5
cd /var/www/html
git clone https://github.com/electerious/Lychee.git
cd Lychee/
chmod -R 777 uploads/ data/

Open web browser
Go to http://192.168.1.x/Lychee
Enter database host, user and password
Click on "Connect"

### Output of the diagnostics (Settings => Diagnostics)

Diagnostics
-----------
Error: Configuration not found. Please install Lychee for additional tests

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
