### ISSUE TITLE
Error: Missing parameters. Can not execute function Lychee\\Modules\\Database::__construct"

### ISSUE THREAD

**Issue by triintisler** [electerious/Lychee#778]
Hey!

I have problem to connect Lychee with my own server and database.

I 've add config.php file and database is created.

Have you any idea, what's wrong?

Thanks.
Triin

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
