### ISSUE TITLE
Setting up Lychee with external database

### ISSUE THREAD

**Issue by flainn** [electerious/Lychee#783]
Hello,

I'm trying to install Lychee with an external database server. 

In other words my Web server (Apache 2.4 on Debian 9) is separate from my database server (MariaDB, also on Debian 9).

I configured the database access permissions to allow lycheeuser@webserver, and I also edited the file /var/www/html/lychee/php/Modules/Config.php to specify $dbHost as my database server.

But when I try to load the Lychee Web page, all I get is

Error: server error or API not found

Have I missed something? I looked for documentation on how to set up Lychee with a non-localhost database server, but haven't found anyone else who is doing it that way.

**Comment by AkselMeola** [comment]
Can you check if the you can log into the mysql server from web server with your lychee credentials ?

I have a Lychee running such that the web server and database are on separate hosts. But you need to have correct access rights for the mysql user.

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
