### ISSUE TITLE
Database in addition to MySQL (PDO/SQLite)

### ISSUE THREAD

**Issue by PeaceCopathe** [electerious/Lychee#83]
Hello,

Would it be possible to add a management database sqlite rather than MySQL?

**Comment by roeme** [comment]
FYI, working on a PR for PDO.

**Comment by tmlmt** [comment]
Switching to PDO would be great! Waiting for sqlite support to install it on my server.

**Comment by electerious** [comment]
@roeme Thanks for helping! Let me know if you have questions.

**Comment by roeme** [comment]
@electerious It's my pleasure! I'm currently grok'ing Database.php. If I understood everything correctly, moving over to PDO requires us to touch all places that call `Database->prepare()`: PDO just doesn't want one to muck around with the prepared query. A PDOStatement comes out of `prepare()`, and that's it for you - you can `execute()` whenever you want, but forget playing around with it (too much) :)

This is in stark contrast to the “old” plumbing, where you essentially got a String back from `prepare()`.

If I'm way off, let me know.

**Comment by electerious** [comment]
This should be correct. Replacing all `Database->prepare()` will be a lot of work. The function is basically to avoid redundancy and to make sure that ALL stuff gets escaped when working with the DB. Maybe there's a different way to use something similar to `Database->prepare()` with PDO? How about execute() within the prepare (e.g.`Database->execute()`)?

Would be great to see a few functions converted to PDO before doing the rest. Maybe we will find a way to do it better after seeing how it actually looks.

**Comment by roeme** [comment]
Yup, I already saw some Queries that will not go into PDO’s `prepare()` - for example, one can’t have placeholders for the tables names, as the DBMS wouldn’t be able come up with a execution plan in this case (PDO’s `prepare()` actually creates a prepared statement on the DB if possible. This could give us a nice speed boost if done correctly – have to check wether we can/need to keep a connection open to the DBMS, and which execution models work with that [CGI, prefork, et al]).

I plan to to handle these queries on a case-by-case basis, and come up with the most fitting solution. For example at roeme/Lychee@12bade3 : the tables names being constants, they could be embedded easily into the query, not loosing any functionality whatsoever over the old code.

btw, I just noticed that the v3 branch is ahead master. I’m currently basing my work on the latter though – a quick look at the changes since master didn’t reveal too much changes in the Backend though. If you feel  I should rather base on v3, let me know.

**Comment by electerious** [comment]
There aren't a lot of back-end changes at the moment, but I'm planning to adjust some things. Not sure if it would be good to keep track with v3. Better ignore it for now.

A case-by-case basis may be needed, but always try to be consistent. Things are getting hard to maintain if you aren't doing so.

**Comment by roeme** [comment]
Sounds good. I'll keep maintainability in mind of course.

**Comment by calimou** [comment]
Hi, I'm looking for an update about this.
The open source offer in terms of good-looking, ready to use, hosted gallery still miss a gallery with a database-as-flat-file. Could be SQLite or anything simpler as flat files that would remove any dependency to a database backend. But I'd be happy with SQLite only :) 
There still is PhotoShow but it's pretty unmaintained and consequently buggy.

Thanks for the great work !

**Comment by roeme** [comment]
@calimou I'm currently quite occupied offline, and so far couldn't spare any time to work on this. I'll try to get back on the horse soon, but it might be quite some time.

**Comment by oupala** [comment]
I agree that having sqlite as a backend would be a real advantage.

**Comment by internetimagery** [comment]
I also agree. Reliance on MYSQL is the only thing keeping me from jumping on this project.

**Comment by bb-Ricardo** [comment]
there is/was a postgresl supported PR but unfortunately it got never merged. https://github.com/electerious/Lychee/pull/395

**Comment by electerious** [comment]
@bb-Ricardo I never really had the time to look closer at it. The PR included tons of changes. Other changes came along and now it's not possible to merge it anymore. I also had trouble getting it working on my machine.

**Comment by roeme** [comment]
*cough*

Still alive, and offline has wound down a bit. Forked afresh. @electerious; anything new to consider since back then?

**Comment by law** [comment]
Any love on the Postgres support?

**Comment by rbman5** [comment]
Postgres support would be great :+1:

**Comment by tobast** [comment]
Anything new on this topic? The old PR #395 now seems totally outdated…

**Comment by hitam4450** [comment]
SQLite 3 support would be great too...

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
