### ISSUE TITLE
[Suggestion] Add pagination for albums view

### ISSUE THREAD

**Issue by kc3lai** [electerious/Lychee#94]
I like the app a lot.  It's the cleanest and slickest self hosted photo management I've seen.  However, I find my browser really struggles trying to load 2000+ albums I accumulated over the last 15 years.  So normally the workflow would be:
1. trying to wait for initial albums view to load
2. scroll down to an interesting album
3. look through the album and back to albums view
4. albums view goes back to the very top, trying to load everything again, back to step 1.

I'm wondering if there's a way to either re-use the initial albums view without explicit reloading or add a pagination mechanism to avoid loading 2000+ albums over and over again?

thanks,

**Comment by rhurling** [comment]
Lazy-Loading of Images would be a start i think

**Comment by ophian** [comment]
Before you add paginate albums view, it would first be recommended to allow sub albums though! ;-)

**Comment by electerious** [comment]
This issue will be closed because I'm not actively working on Lychee anymore. The repository of Lychee will stay available, but the main development continues under the [Lychee Organisation](https://github.com/LycheeOrg). A fork maintained by the community. Important issues have been migrated. Feel free to re-add your issue(s) when necessary.
