### ISSUE TITLE
sorting: albums and photos

### ISSUE THREAD

**Issue by GustavePate** [electerious/Lychee#98]
Hello,

I just upgraded to lychee 2.1.
I had a album sort problem last time we speak. I wanted my albums to be displayed  sorted by names and I figured out how to patch your code to make it  possible.

With this new version, I suppose the album sorting is done somewhere in the javascript magic ;) Modification of the select query of [album.php](https://github.com/electerious/Lychee/blob/master/php/modules/album.php#L34-35) does nothing on the display order.

I had to modify lycheesync to rewrite album ids... imagine the mess ;)

## 1/  Album sorting

Anyway, I saw a wonderfull new option that enable us to choose the sorting order of photos.
Please add the same option on the album sorting order ;)

## 2/ Photos sorting
The function "sort by upload time" sorts "only by time". What happens when you have a album with photos uploaded on different days and wants to keep the uploaded order ? 

It could have been:
       ```order by sysdate, systime```

But really, really it should be:
       ```order by takedate, taketime```

Anyway, I don't see a date or time mention in [settings.php](https://github.com/electerious/Lychee/blob/master/php/modules/settings.php#L88)

I had to set ```description = takedate + taketime``` to have a descent ordering in my albums. It's why I upvoted #93 

I really think that lychee is not suitable for hosting familly photos while these two issues photos and album sorting are not solved. 

The new functionnalities of the 2.X version are very impressive but not as essential as having the ability to control the order your photos display on screen.

I look like a bit negative here. :|
It's just to insist on the sorting problem, I really enjoyed the new version !
You even fixed the orientation problem I struggle to fix in lycheesync. Now I can comment my code ;)

Keep up the good work !

**Comment by ophian** [comment]
The strange thing is, you can't even force that with a query appendix `ORDER BY title ASC`.

I think I narrowed to the issue. It seems to be a matter of json_encode in admin (and guest) `json_encode($album->getAll(false))`, using some own indexing sorting and rewriting any pre sorted delivery, while the PHP array is not sequential [0, 1, 2].
Using `echo json_encode(array_values($album->getAll(false)));` could help us here, but has a follow-up error. (It is not easy to debug at all and I wonder how you actually do this...)
What do you think? Might that be?

**Comment by ophian** [comment]
Best so far is adding a [] to `$return['albums'][$album['id']] = $album;` to be '$return['albums'][][$album['id']] = $album;´ in albums::getAll(), which returns the list as an array, not object, and then does not trigger the json_encode() internal sorting. But it has follow-up issues - for the albums.parse...

**Comment by ophian** [comment]
@electerious 

Ok, I found a solution, which looks a little weird, I know, but I could not do this any else.
	
We have to deal with objects and arrays and json_encode not touching the delivered sort of (sequential index) keys, which was sorted by `id` before and looked like this
```albums: {3: {id: "3", title: "Creative", public: "1", sysdate: "March 2015",…}```

What I tried to get, was an object with an untouched sorted albums "array", when gone through json_encode().

In Albums.php `getAll()` I ordered the albums "array" by 'title':
```php
		$query = Database::prepare($this->database, 'SELECT id, title, public, sysstamp, password FROM ? WHERE public = 1 AND visible <> 0 ORDER BY title ASC', array(LYCHEE_TABLE_ALBUMS));
		if ($public===false) $query = Database::prepare($this->database, 'SELECT id, title, public, sysstamp, password FROM ? ORDER BY title ASC', array(LYCHEE_TABLE_ALBUMS));
```

and in Admin.php `getAlbums()` I newly arranged the albums:
```php
	# Album functions
	private function getAlbums() {

		$album = new Album($this->database, $this->plugins, $this->settings, null);

        $a = $album->getAll(false);

        $x['smartalbums'] = $a['smartalbums'];
        $x['albums'] = array_values($a['albums']); // get array albums in right order
        $x['num'] = $a['num'];

        unset($a);

        echo json_encode($x);

	}
```

This delivered the albums "array" in the right order [A-Z] now. But it was still displayed wrong on screen, in reverse order from [Z to A].
I tried around a lot with sorting functions, without any real access, since this are objects. (Maybe you have an idea where further on this is read in reverse order.)

It then became necessary to cheat this "mysterious" display order, by changing the db order to `DESC`, which is the opposite of what I wanted.
```php
		$query = Database::prepare($this->database, 'SELECT id, title, public, sysstamp, password FROM ? WHERE public = 1 AND visible <> 0 ORDER BY title DESC', array(LYCHEE_TABLE_ALBUMS));
		if ($public===false) $query = Database::prepare($this->database, 'SELECT id, title, public, sysstamp, password FROM ? ORDER BY title DESC', array(LYCHEE_TABLE_ALBUMS));
```

Now everything is fine. The array is coming-in sorted as [Z-A] and is displayed in reverse order on screen from [A-Z]!
```albums: [{id: "29", title: "Zero", public: "1", sysdate: "March 2015",…},…]```

Sadly we can not just use `'SELECT id, title, public, sysstamp, password FROM ? ' . $this->settings['sorting']` because of this reverse order display issue.

What do you think?

**Comment by ophian** [comment]
I solved the `$this->settings['sorting']` and `reverse sort` issue in Album.php. But you still need to keep the changes for admin and guest as showed.
```php
	public function getAll($public) {

.....

		$query = Database::prepare($this->database, 'SELECT id, title, public, sysstamp, password FROM ? WHERE public = 1 AND visible <> 0 ' . $this->settings['sorting'], array(LYCHEE_TABLE_ALBUMS));
		if ($public===false) $query = Database::prepare($this->database, 'SELECT id, title, public, sysstamp, password FROM ? ' . $this->settings['sorting'], array(LYCHEE_TABLE_ALBUMS));

		# Execute query
		$albums = $this->database->query($query);

		....

		while ($album = $albums->fetch_assoc()) {
			.... gather and return ....
		}

		# Cheat json_encode reverse order output by creating a reverse albums array order already
		$return['albums'] = array_reverse($return['albums']);

		# Num of albums
		$return['num'] = $albums->num_rows;

		....

		return $return;

	}
```
This, since the strange reverse order display thing is a matter of json_encode.

**Comment by ophian** [comment]
Ok one last try, which would leave both `getAlbums()` methods untouched.
Change above
```php
        # Cheat json_encode reverse order output by creating a reverse albums array order already
        $return['albums'] = array_reverse($return['albums']);
```
to
```php
        # Cheat json_encode reverse order output and non-array by creating a reverse albums array order already
        $ret['albums'] = array_values(array_reverse($ret['albums']));
```
and keep the `$this->settings['sorting']` in the queries.

Thats it!

**Comment by electerious** [comment]
The order gets inverted in the front-end: https://github.com/electerious/Lychee/blob/master/src/scripts/view.js#L160 This is a wanted behavior, because the content should start with the newest albums (I’m inverting the sorting in the front-end, because it wasn’t working in the back-end). I will take a look at your solution by time. Maybe you can open a PR based on the v3 branch?

**Comment by ophian** [comment]
Does this really have any access on the 3.x branch? I have never seen view.php happen to appear. Or is that happen completely in DOM? I could not even test this, since I can't build all that stuff together.
For what are the files view.js and view.php build for?

I see that special line gathered to main.js as `t=build.album(this)+t`. You don't actually need this any more (reverted), since the sort happens by query and user cpnfig sorting now and could be `t=t+build.album(this)` which would avoid the need of the upper array_reverse(). The array_values() would still be a need to make albums an array, to not make json methods touch the sorting.

**Comment by ophian** [comment]
Doing this the way discribed, would now even allow to have another user sorting option, by ID (ASC/DESC). Then this would be totally free in use.

**Comment by ophian** [comment]
Hmm bad, I just discovered that this has some dependencies with opening frontend albums. My backend is working just fine with all my albums, which do not have a sequential id index, since I have about 24 albums with last id 29, starting with 2 and some missing ones inbetween, due to the "wrong" import of multilevel dir albums.
My last 5 albums (in the "array") do not open in the frontend, throwing errors in Firefox `TypeError: albums.json.albums[e] is undefined` and in Chrome with `Uncaught TypeError: Cannot read property 'password' of undefined` (which field password settings are identical to all other albums). I seems as like the internal count or something is messed up now, or if there are some more reverse sorting relating code parts on frontend side. Backend is doing well though!

**Comment by ophian** [comment]
And the json sorting issue does also hit the inner album content sorting. I have the option sorting by title ASC enabled and it does not do this, when checked more deeply. It all is arranged by ID, which looks like the json sort issue, while `{...}` and not `[{...}]` and will for sure need this array_values() to array conversion too. (I am not able to say where en detail at the moment!)

**Comment by electerious** [comment]
So our main problem is that `json_encode` sorts our array to an unwanted order and we need to prevent this behavior by adjusting the array? In this case we need to adjust the front-end to work with the new response from the server? (Like @dixy did: https://github.com/electerious/Lychee/pull/104)?

Do you know why it’s possible to sort photos inside an album without loosing the original order? `Album::get()` works fine for some reason.

**Comment by ophian** [comment]
> So our main problem is that json_encode sorts our array to an unwanted order and we need to prevent this behavior by adjusting the array?

Yes partly, as one part of the issue.
for inner album images the arrays is like
````php
<pre>Array
(
    [14273621463944] => Array
        (
            [id] => 14273621463944
            [title] => blue Moon
            [tags] => 
            [public] => 0
            [star] => 0
            [album] => 29
            [thumbUrl] => uploads/thumb/hashofbluemoon.jpeg
            [url] => uploads/big/hashofbluemoon.jpg
            [cameraDate] => 0
            [sysdate] => 26 March 2015
            [previousPhoto] => 
            [nextPhoto] => 14273621459454
        )

    [14273621459454] => Array
        (
            [id] => 14273621459454
            [title] => fatal Morning
            [tags] => 
            [public] => 0
            [star] => 0
            [album] => 29
            [thumbUrl] => uploads/thumb/hashoffatalmorning.jpeg
            [url] => uploads/big/hashoffatalmorning.jpg
            [cameraDate] => 0
            [sysdate] => 26 March 2015
            [previousPhoto] => 14273621463944
            [nextPhoto] => 14273621460114
        )
...
```
but should better be
```php
<pre>Array
(
    [0] => Array
        (
            [id] => 14273621463944
            [title] => blue Moon
            [tags] => 
            [public] => 0
            [star] => 0
            [album] => 29
            [thumbUrl] => uploads/thumb/hashofbluemoon.jpeg
            [url] => uploads/big/hashofbluemoon.jpg
            [cameraDate] => 0
            [sysdate] => 26 March 2015
            [previousPhoto] => 
            [nextPhoto] => 14273621459454
        )

    [1] => Array
        (
            [id] => 14273621459454
            [title] => fatal Morning
            [tags] => 
            [public] => 0
            [star] => 0
            [album] => 29
            [thumbUrl] => uploads/thumb/hashoffatalmorning.jpeg
            [url] => uploads/big/hashoffatalmorning.jpg
            [cameraDate] => 0
            [sysdate] => 26 March 2015
            [previousPhoto] => 14273621463944
            [nextPhoto] => 14273621460114
        )
...
```
which can be done by `$return['content'] = array_values($return['content']);` in get() 
```php
			# Add to return
			$return['content'][$photo['id']] = $photo;

		}
        $return['content'] = array_values($return['content']);
....
```

Then the sequential key order is indexed and will not trigger the json internal sorts.
Same in getAll() for the ['albums'] array.

This is part one of the problem.
This array_values conversion works well for the `albums` array, turning an "object like array" {...} into and "array with objects" `[{...}]`. Doing this with an albums `content` array works internally, as you can see by the upper example array and sets a right index. But it does not turn into `[{...}]`. I don't know why yet. (Is that parsed by json_encode ?)

Now as long as this index thing isn't solved, a db based ORDER BY sort will never pop up, since it gets overwritten by the json methods.

Fixing this and the adding ORDER BY to the queries will need to revert all reverse order changes later on (in the js). For the albums open and "shortcut" issue for the frontend I still have no idea why his happens after re-indexing the arrays.

**Comment by ophian** [comment]
> Do you know why it’s possible to sort photos inside an album without loosing the original order? Album::get() works fine for some reason.

I don't think it does. You really need an album which is/was totally unsorted on upload. Then you will see that is is sorted by the hashed-ID indexes and not by the inner sorting table field. Most of mine fit too, that is why I never noticed before, since I never looked into that deep (and maybe due to not parse through a json method, does it?).

**Comment by ophian** [comment]
I solved the missing `[]` for the content array
We have to place the `$return['content'] = array_values($return['content']);`
a little later, since next and prev need to be re-indexed too.
````php
...
		while ($photo = $photos->fetch_assoc()) {

			# Turn data from the database into a front-end friendly format
			$photo = Photo::prepareData($photo);

			....

			# Add to return
			$return['content'][$photo['id']] = $photo;

		}

		if ($photos->num_rows===0) {

			# Album empty
			$return['content'] = false;

		} else {

			# Enable next and previous for the first and last photo
			$lastElement	= end($return['content']);
			$lastElementId	= $lastElement['id'];
			$firstElement	= reset($return['content']);
			$firstElementId	= $firstElement['id'];

			if ($lastElementId!==$firstElementId) {
				$return['content'][$lastElementId]['nextPhoto']		= $firstElementId;
				$return['content'][$firstElementId]['previousPhoto']	= $lastElementId;
			}

		}

		$return['content'] = array_values($return['content']);// set as real re-indexed array

		$return['id']	= $this->albumIDs;
		$return['num']	= $photos->num_rows;
...
```
Now the inner album sorting is sorted by the sort option only!

**Comment by ophian** [comment]
Tobias, I am sorry I'm spamming this thread :)
This re-indexing has not even follow-up dependencies in correct reading for some albums, it now does have issues to open single (uploads/big) images too. So all follow up array readings (ie the next/prev readment) needs to fetch up these changes, I assume.

**Comment by electerious** [comment]
Hey @ophian, I lost the overview of all the things you tried ;) Could you open a PR with your final solution and a breakdown of what should be done in the front-end (e.g. removing the inverting)?

**Comment by electerious** [comment]
In work: https://github.com/electerious/Lychee/commit/e64e29f81f42fdf5c04fa795ce9f38c5a58e03ee

**Comment by electerious** [comment]
Album sorting here we go!!! Please take a look at the develop branch and let me know if everything works :)

**Comment by ophian** [comment]
I added your commit "Added album sorting https://github.com/electerious/Lychee/commit/90ac81acf12a47c60d46ba7ff4b8e3d690eb4a64" yesterday - which really fixes the accessibility things, but I still had to add the sorting to the db query in Album.php and revert the reverse album sorting.in view.js.
``` js
					// Display albums in reverse order
					albumsData = build.album(this) + albumsData;
```
changing to 
``` js
					albumsData = albumsData + build.album(this);
```
in main.js = ````t=t+build.album(this)```` Then all is fine, so far (at first glance)!
Thanks.

**Comment by electerious** [comment]
There's more than one commit ;) You need all of them. Try switching to develop. The database will be updated automatically and the reverse album sorting has been removed.

**Comment by ophian** [comment]
Yes, I fetched your commit without knowing there were some follow ups.

**Comment by electerious** [comment]
@ophian Have you tried it? Is it working for you?

**Comment by ophian** [comment]
Yes fine. Thanks!
